### PR TITLE
change mod_ping Timers using maps instead of dict

### PR DESCRIPTION
**Pull request by cclam0827**
Since OTP 18 maps function more efficient than dict, change the mod_ping using dict instead.

### CODE REVIEW

**Comment by weiss** [comment]
I'd use `maps:find/2` rather than `catch maps:get/2`.

**Comment by cclam0827** [comment]
@weiss Thanks for your suggestion, I have changed to use `maps:find` instead :)

**Comment by badlop** [comment]
Looking at the Erlang/OTP release notes, Maps was introduced in 17.0, and performance was improved in 18.0. ejabberd already requires 17.1, so this patch does not increase the requirements, and that's always a good thing :)

**Comment by zinid** [comment]
@badlop we actually decided not to merge it

**Pull request merged**
