### PR TITLE
rebar3 support for main build process

### PR DESCRIPTION
**Pull request by nosnilmot**
This adds support for building, and installing, ejabberd using rebar3

A --with-rebar=/path/to/rebar3 option is added to configure to specify which rebar to use

rebar2 compatibility is maintained, and the bundled rebar2 is still used by default

### CODE REVIEW

**Comment by badlop** [comment]
Hi, it compiles perfectly with the built in rebar2, but when I try with rebar3, it complains about _configure_ not found. Do you have any clue about the problem?

```
$ git clone https://github.com/nosnilmot/ejabberd.git
$ cd ejabberd/
$ git checkout -b 3395 origin/rebar3

$ ./autogen.sh
$ ./configure --with-rebar=/home/badlop/git/processone/rebar3/rebar3
checking whether make sets $(MAKE)... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking for a sed that does not truncate output... /usr/bin/sed
checking for erl... /usr/bin/erl
checking for erlc... /usr/bin/erlc
checking for epmd... /usr/bin/epmd
checking for erl... /usr/bin/erl
checking for erlc... /usr/bin/erlc
checking for Erlang/OTP root directory... /usr/lib/erlang
checking for escript... /usr/lib/erlang/bin/escript
checking for make... make
checking Erlang/OTP version... ok
configure: creating ./config.status
config.status: creating Makefile
config.status: creating vars.config
config.status: creating src/ejabberd.app.src

$ make
...
===> Analyzing applications...
===> Compiling configure_deps
===> Verifying dependencies...
/home/badlop/git/ejabberd/_build/default/lib/eimp
/home/badlop/git/ejabberd/_build/default/lib/ezlib
/home/badlop/git/ejabberd/_build/default/lib/fast_tls
/home/badlop/git/ejabberd/_build/default/lib/fast_xml
/home/badlop/git/ejabberd/_build/default/lib/fast_yaml
/home/badlop/git/ejabberd/_build/default/lib/stringprep
/usr/lib/erlang/bin/escript /home/badlop/git/processone/rebar3/rebar3 compile && :> _build/default/lib/.built
===> Analyzing applications...
===> Compiling configure_deps
===> Verifying dependencies...
sh: 1: ./configure: not found
===> Hook for {pc,compile} failed!

make: *** [Makefile:132: _build/default/lib/.built] Error 1
```

**Comment by nosnilmot** [comment]
> Hi, it compiles perfectly with the built in rebar2, but when I try with rebar3, it complains about _configure_ not found. Do you have any clue about the problem?

Yes, we need hex packages that include _configure_ to be released and referenced by ejabberd. I already submitted the necessary packaging fixes to those packages:

epam: processone/epam#10
esip: processone/esip#10
ezlib: processone/ezlib#3
fast_tls: processone/fast_tls#48
fast_xml: processone/fast_xml#42
fast_yaml: processone/fast_yaml#17
stringprep: processone/stringprep#10

Until those are available, to test this PR (or even building with rebar3 before this PR) you can manually copy in vars.config.in and configure files from git for each of the above repos into the _build/default/lib tree after dependencies have been fetched initially. You'll probably also need updated rebar.config and esip_socket.erl from changes in processone/esip#9

**Comment by badlop** [comment]
Right, following your steps it works :)

**Comment by nosnilmot** [comment]
> Right, following your steps it works :)

Thanks for merging this. Can I persuade you to take a look at #3399 too?

**Pull request merged**
