### PR TITLE
update spec from custom github repo ext_mod.erl

### PR DESCRIPTION
**Pull request by HeroPD**
issue #1738

i modified ext_mod.erl little bit

i created repo for test case
ejabberdctl modules_update_specs_from_github https://github.com/HeroPD/ejabberd_module_test

### CODE REVIEW

**Comment by cromain** [comment]
This PR is not completely needed, as ext_mod already supports extra contrib:
```
(ejabberd@localhost)1> ext_mod:add_sources(mod_test, "https://github.com/HeroPD/ejabberd_module_test").
ok
(ejabberd@localhost)2> ext_mod:install(mod_test).
/home/chris/.ejabberd-modules/sources/ejabberd_module_test/mod_test/src/mod_test.erl:3: Warning: undefined callback function depends/2 (behaviour 'gen_mod')
/home/chris/.ejabberd-modules/sources/ejabberd_module_test/mod_test/src/mod_test.erl:3: Warning: undefined callback function mod_opt_type/1 (behaviour 'gen_mod')
ok
(ejabberd@localhost)3> ext_mod:installed(mod_test).
true
```
The thing is actual implementation lack automatic update of such repository. (the same way as ejabberd-contrib). I'll check this and also your second commit about compile_includes/0

**Comment by cromain** [comment]
I've adopted a simpler approach, allowing custom repository to be updated with ext_mod:update()
contributed modules can also depend at each others (installed module include directory are added to compilation path)

**Comment by HeroPD** [comment]
I have include folders in subdirectory as `deps/*/include` . I am adding them using `code:add_patha/1` so second commit was about adding subdirectory `include` in module compiler that way we don't have to copy every `*.hrl` files

**Comment by HeroPD** [comment]
Does ext mode support rebar?

**Pull request closed without merging**
