### PR TITLE
External Component Connection Hooks

### PR DESCRIPTION
**Pull request by xmppjingle**
External Component Connection Hooks 

Event List:
component_connected(ComponentAddress) -> ok
component_disconnected(ComponentAddress, Reason) -> ok

### CODE REVIEW

**Comment by zinid** [comment]
Isn't it better to call `component_disconnect` hook in `terminate/3` when StateName is `session_established` (along with de-registering route)? Because in your version if an `ejabberd_service` process fails the hook won't be called.

**Comment by xmppjingle** [comment]
Thanks for the suggestion. I will make the modifications and push again.

**Comment by xmppjingle** [comment]
Suggestion applied and Reason added upon disconnection

**Comment by mremond** [comment]
Thanks !

**Pull request merged**
