### PR TITLE
[fix] fix mysql.sql archive origin_id

### PR DESCRIPTION
**Pull request by heyanyanchina123**

### CODE REVIEW

**Comment by prefiks** [comment]
Thank you

**Comment by weiss** [comment]
```sql
ALTER TABLE archive ADD COLUMN origin_id origin_id(191) NOT NULL DEFAULT '';
```

Shouldn't the type be `varchar(191)` instead?

**Comment by prefiks** [comment]
Ah, indeed, i will change that.

**Comment by prefiks** [comment]
Changed in d2a3fe3ed2956d392fdba9d0d9e713c1bd8169ff

**Pull request merged**
