### PR TITLE
avoid preparing statements for pgsql

### PR DESCRIPTION
**Pull request by oxpa**
When using with pgbouncer or other Postgresql balancer ejabberd doesn't behave well as it uses anonymous prepared statements which are valid for a single connection only.

The proposed change removes prepared statements from ejabberd and instead relies on p1_pgsql to prepare and execute statement (see p1_pgsql/pull/5).

This change also requires new pq_pgsql version, but I can't change rebar config as my pull request to pgsql is not yet accepted (at the time of me writing this message).

I'm not 100% sure if this will work properly in all cases, but I'm willing to fix any mistakes I left behind.

### CODE REVIEW

**Comment by licaon-kter** [comment]
So this doesn't work? https://docs.ejabberd.im/archive/20_04/toplevel/#sql-prepared-statements

**Comment by oxpa** [comment]
Ouch!
I actually patched an earlier version of ejabberd which didn't have this option and then applied the patch to current version.
So it may happen the patch doesn't make sense anymore :-\

**Comment by Neustradamus** [comment]
@oxpa: With latest ejabberd, your patch is not needed?
Have you tested without?

**Comment by oxpa** [comment]
Yes, this patch is not needed on newer versions of ejabberd

**Pull request closed without merging**
