### PR TITLE
Support for oracle

### PR DESCRIPTION
**Pull request by softctrl**
I don't receive error using riak here, and also now i am using at least all modules (those with odbc support) with odbc, and also i make some tests using pgsql.

### CODE REVIEW

**Comment by softctrl** [comment]
Hello some one can help?
that`s is the travis error:
The command "sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 5072E1F5" failed and exited with 2 during .
Your build has been stopped.

so, don`t appears an error on the pull request to me.

**Comment by softctrl** [comment]
The log 
```
Using worker: worker-linux-da6418d7-2.bb.travis-ci.org:travis-linux-10
system_info
Build system information
Build language: erlang
Build image provisioning date and time
Wed Feb  4 18:22:50 UTC 2015
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04 LTS
Release:	12.04
Codename:	precise
Linux Version
2.6.32-042stab090.5
Cookbooks Version
23bb455 https://github.com/travis-ci/travis-cookbooks/tree/23bb455
GCC version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
LLVM version
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Pre-installed Ruby versions
ruby-1.9.3-p551
Pre-installed Node.js versions
v0.10.36
Pre-installed Go versions
1.4.1
Redis version
redis-server 2.8.19
riak version
2.0.2
MongoDB version
MongoDB 2.4.12
CouchDB version
couchdb 1.6.1
Neo4j version
1.9.4
Cassandra version
2.0.9
RabbitMQ Version
3.4.3
ElasticSearch version
1.4.0
Installed Sphinx versions
2.0.10
2.1.9
2.2.6
Default Sphinx version
2.2.6
Installed Firefox version
firefox 31.0esr
PhantomJS version
1.9.8
ant -version
Apache Ant(TM) version 1.8.2 compiled on December 3 2011
mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/maven
Java version: 1.7.0_76, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "2.6.32-042stab090.5", arch: "amd64", family: "unix"
git.checkout
1.13s$ git clone --depth=50 https://github.com/processone/ejabberd.git processone/ejabberd
Cloning into 'processone/ejabberd'...
remote: Counting objects: 809, done.
remote: Compressing objects: 100% (504/504), done.
remote: Total 809 (delta 413), reused 477 (delta 297), pack-reused 0
Receiving objects: 100% (809/809), 1.61 MiB | 0 bytes/s, done.
Resolving deltas: 100% (413/413), done.
Checking connectivity... done.
$ cd processone/ejabberd
0.52s$ git fetch origin +refs/pull/813/merge:
remote: Counting objects: 101, done.
remote: Compressing objects: 100% (74/74), done.
remote: Total 101 (delta 83), reused 44 (delta 27), pack-reused 0
Receiving objects: 100% (101/101), 20.08 KiB | 0 bytes/s, done.
Resolving deltas: 100% (83/83), completed with 28 local objects.
From https://github.com/processone/ejabberd
 * branch            refs/pull/813/merge -> FETCH_HEAD
$ git checkout -qf FETCH_HEAD
services
5.99s$ sudo service riak start
17.5 is not installed. Downloading and installing pre-build binary.
0.92s$ kerl update releases
Getting the available releases from erlang.org...
The available releases are:
R10B-0 R10B-10 R10B-1a R10B-2 R10B-3 R10B-4 R10B-5 R10B-6 R10B-7 R10B-8 R10B-9 R11B-0 R11B-1 R11B-2 R11B-3 R11B-4 R11B-5 R12B-0 R12B-1 R12B-2 R12B-3 R12B-4 R12B-5 R13A R13B01 R13B02-1 R13B02 R13B03 R13B04 R13B R14A R14B01 R14B02 R14B03 R14B04 R14B_erts-5.8.1.1 R14B R15B01 R15B02 R15B02_with_MSVCR100_installer_fix R15B03-1 R15B03 R15B R16A_RELEASE_CANDIDATE R16B01 R16B02 R16B03-1 R16B03 R16B 17.0-rc1 17.0-rc2 17.0 17.1 17.3 17.4 17.5 18.0 18.1
1.41s$ wget https://s3.amazonaws.com/travis-otp-releases/ubuntu/$(lsb_release -rs)/erlang-17.5-x86_64.tar.bz2
--2015-11-02 10:40:05--  https://s3.amazonaws.com/travis-otp-releases/ubuntu/12.04/erlang-17.5-x86_64.tar.bz2
Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.19.179
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.19.179|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 53793144 (51M) [application/x-tar]
Saving to: `erlang-17.5-x86_64.tar.bz2'
100%[======================================>] 53,793,144  42.5M/s   in 1.2s    
2015-11-02 10:40:07 (42.5 MB/s) - `erlang-17.5-x86_64.tar.bz2' saved [53793144/53793144]
9.23s$ tar xf erlang-17.5-x86_64.tar.bz2 -C ~/otp/
0.01s0.01s0.01s$ source $HOME/otp/17.5/activate
before_install.1
0.01s$ sudo sed -i -e s/table_cache/table_open_cache/ -e /log_slow_queries/d /etc/mysql/my.cnf
60.21s$ sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 5072E1F5
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --secret-keyring /tmp/tmp.1HWeidUCdO --trustdb-name /etc/apt/trustdb.gpg --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d//apt.postgresql.org.gpg --keyserver pgp.mit.edu --recv-keys 5072E1F5
gpg: requesting key 5072E1F5 from hkp server pgp.mit.edu
gpgkeys: key 5072E1F5 not found on keyserver
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
The command "sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 5072E1F5" failed and exited with 2 during .
Your build has been stopped.
```

**Comment by weiss** [comment]
> The command "sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 5072E1F5" failed

This was a temporary error in one of the two builds.  I restarted the build, but `make test` is now timing out.

(BTW, I didn't look into your changes, but if there's interest in merging it and the `make test` issue is solved, all those "refactoring" commits should be [squashed][1].)

[1]: http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request

**Comment by softctrl** [comment]
hi, can you see the ejabberd logs? because here in my project don`t have error at all.

so, if you have access to the ejabberd logs maybe there is some important info there.

**Comment by weiss** [comment]
> can you see the ejabberd logs?

I didn't run `make test` with your changes locally, so I only see the [output on Travis][1].

> here in my project don`t have error at all.

Did you run `make test`?

[1]: https://travis-ci.org/processone/ejabberd/jobs/88759099`

**Comment by softctrl** [comment]
i did create one environment here with riak too, and my make test dont show any error. I will create a new vm here to test again

**Comment by softctrl** [comment]
so, i will take some time, soon i get any data i will post here

**Comment by softctrl** [comment]
at least i am using oracle here :D

**Comment by softctrl** [comment]
hy dude, how are you? So, i just did up your vagrant machine, and i compile and execute the tests of the main ejabberd project (https://github.com/processone/ejabberd),  and i just receive this message:

{ejabberd_SUITE,init_per_group,54}
{test_case_failed,{failed_to_create_sql_tables,mysql, {aborted, "#HY000The used table type doesn't support FULLTEXT indexes"}}}

**Comment by prefiks** [comment]
It probably means that your mysql is too old, i think you need to have version 5.6 or newer.

**Comment by softctrl** [comment]
i will need to change the mysql table to myisam. But i just make a git clone of
https://github.com/processone/ejabberd-vagrant-dev

**Comment by softctrl** [comment]
just into the vagrant machine
mysql --version
mysql  Ver 14.14 Distrib 5.5.46, for debian-linux-gnu (x86_64) using readline 6.2

**Comment by softctrl** [comment]
i will set the table for myisam,

**Comment by softctrl** [comment]
i just change my database for myisam default and your mysql.sql script to use myisam inted innodb, and the tests go on, until now not one single error.

**Comment by softctrl** [comment]
/usr/local/lib/erlang/bin/escript rebar skip_deps=true ct
==> ejabberd (ct)
DONE.
Testing projects.ejabberd: TEST COMPLETE, 175 ok, 0 failed of 175 test cases

vagrant@vagrant:/projects/ejabberd$

**Comment by softctrl** [comment]
so, i am testing the oracle support right now.

**Comment by softctrl** [comment]
so, after that, i am receiving 15 failed tests

60	ejabberd_SUITE	single_user	roster_ver	< >	120.000s	FAILED	{timetrap_timeout,{suite,recv,217}}
67	ejabberd_SUITE	test_muc_register	muc_register_master	< >	0.284s	FAILED	{ejabberd_SUITE,muc_register_nick,1388}
{badmatch,{iq,<<"2336516712">>,result,undefined, {jid,<<...}
69	ejabberd_SUITE	test_roster_subscribe	roster_subscribe_master	< >	120.000s	FAILED	{timetrap_timeout,{suite,recv,217}}
70	ejabberd_SUITE	test_roster_subscribe	roster_subscribe_slave	< >	120.000s	FAILED	{timetrap_timeout,{suite,recv,217}}
72	ejabberd_SUITE	test_offline	offline_slave	< >	120.000s	FAILED	{timetrap_timeout,{suite,recv,217}}
73	ejabberd_SUITE	test_old_mam	mam_old_master	< >	120.000s	FAILED	{timetrap_timeout,{ejabberd_SUITE,mam_old_master}}
74	ejabberd_SUITE	test_old_mam	mam_old_slave	< >	120.000s	FAILED	{timetrap_timeout,{ejabberd_SUITE,mam_old_slave}}
75	ejabberd_SUITE	test_new_mam	mam_new_master	< >	120.000s	FAILED	{timetrap_timeout,{ejabberd_SUITE,mam_new_master}}
76	ejabberd_SUITE	test_new_mam	mam_new_slave	< >	120.000s	FAILED	{timetrap_timeout,{ejabberd_SUITE,mam_new_slave}}
81	ejabberd_SUITE	test_vcard_xupdate	vcard_xupdate_master	< >	120.000s	FAILED	{timetrap_timeout,{suite,recv,217}}
82	ejabberd_SUITE	test_vcard_xupdate	vcard_xupdate_slave	< >	120.000s	FAILED	{timetrap_timeout,{suite,recv,217}}
83	ejabberd_SUITE	test_roster_remove	roster_remove_master	< >	120.000s	FAILED	{timetrap_timeout,{suite,recv,217}}
84	ejabberd_SUITE	test_roster_remove	roster_remove_slave	< >	120.000s	FAILED	{timetrap_timeout,{suite,recv,217}}
98	ejabberd_SUITE	test_muc_register	muc_register_master	< >	0.275s	FAILED	{ejabberd_SUITE,muc_register_nick,1388}
{badmatch,{iq,<<"4191961972">>,result,undefined, {jid,<<...}
129	ejabberd_SUITE	test_muc_register	muc_register_master	< >	0.278s	FAILED	{ejabberd_SUITE,muc_register_nick,1388}
{badmatch,{iq,<<"3869995154">>,result,undefined, {jid,<<...}



well, i will fix this and soon as i can i will make another pull request.

thanks

**Pull request closed without merging**
