### PR TITLE
Websocket connection shaping

### PR DESCRIPTION
**Pull request by fdie**
It seems shapers currently don't apply to clients connected through "websocket" to the server.
I can't figure out the reason for the question mark in "ejabberd_http_ws.erl" :

```erlang
change_shaper({http_ws, _FsmRef, _IP}, _Shaper) ->
    %% TODO???
    ok.
```

Nevertheless, I applied the same kind of gen_tcp/shaping as used on raw connections to websocket connections too.

### CODE REVIEW

**Comment by licaon-kter** [comment]
You've mixed them up, maybe rebase or resubmit so you don't commit those errors too. Same for the other PR.

**Comment by fdie** [comment]
Indeed, I missed to create 2 branches for the "mod_ping" / "websockets shaping" patches :-(
That's why I reverted some commits, now:
-  "mod_ping" is in my "fdie:master" branch
- "websockets shaping" is in a dedicated "fdie:websocket_shaping" branch

The pull requests should be fine.

If they could be undone, I could also resubmit new ones using two dedicated fix branches...

Thx

**Comment by prefiks** [comment]
Hello,

I did merge that change (after updating it to modifications to websocket files), so let's close it.

Thank you for your contribution!

**Comment by Neustradamus** [comment]
Commit: https://github.com/fdie/ejabberd/commit/cd88d342b99fdc710e3ef91313e54321b908237a

**Pull request closed without merging**
