### PR TITLE
Build docker image from context rather than cloning in the container

### PR DESCRIPTION
**Pull request by RomanHargrave**
Presently the docker build process for ejabberd does not work well for local snapshot builds, as ejabberd is cloned inside the container during the build process. Most of the projects I have encountered adopt a strategy of providing a Dockerfile located in the root of the repository, and copy files from the same directory into the container to perform the build. This strategy serves developers wishing to build local images as well as CI pipelines that can simply check the repository out and run the build.

This commit moves the Dockerfile and its dependencies to the root of the repository or into a folder for container-specific files, and copies the code to be built out of the context (`COPY . ./ejabberd`) instead of cloning it, making no other changes to the build. This enables local builds (`docker build .` or `podman build .` both work) and GHA builds. I am running builds produced in this manner in a Kubernetes cluster, and rolled them out over official builds without any issue. Such builds are accessible [at my fork](https://github.com/RomanHargrave/ejabberd/pkgs/container/ejabberd) (with changes from the WIP #3893.)

### CODE REVIEW

**Comment by badlop** [comment]
Thanks! That "git checkout" annoyed me too sometimes. With your improvement, it is a lot easier to build images for testing local changes.

Also, maybe the VERSION argument probably can be avoided now. That would also allow to reduce other workarounds that I introduced for paths and ejabberdctl script :)

However, I see you introduced some changes unrelated to this feature. And in fact, those changes are not directly motivated by this improvement, they seem purely cosmetical/personal:

1. Renamed `.github/container` to `docker/`

2. Moved Dockerfile to `/`

Now that the context is `.`, the `-f` argument can be used to set the Containerfile. Instead of
`docker build .github/container`, using `docker build -f .github/container/Dockerfile .`

In fact, Dockerfile could be renamed to Containerfile or any other name, as there's nothing tied to "Docker" in it.

3. Deleted `.github/container/ejabberd-container-install.bat`

Some examples that contradict the changes 1. and 2.:
https://github.com/erlang/otp/tree/master/.github/dockerfiles
https://github.com/maranda/metronome/tree/master/docker
https://github.com/esl/MongooseIM/tree/master/tools/pkg

In this sense, I reduced your commit to the barely minimum to implement the desired improvement, and seems to work perfectly for me. Can you take a look at this simplified patch? If you confirm it's good enough, it would be great if you force-push your PR into a simple commit with a patch like that. Once merged, I'd work in removing VERSION and simplifying paths...

<details>

```diff
diff --git a/.dockerignore b/.dockerignore
index 94b549649..b825bcd1f 100644
--- a/.dockerignore
+++ b/.dockerignore
@@ -1,3 +1,46 @@
 .git
 .win32
 .examples
+*.swp
+*~
+\#*#
+.#*
+.edts
+*.dump
+/Makefile
+/config.log
+/config.status
+/config/releases.exs
+/configure
+/aclocal.m4
+/*.cache
+/deps/
+/.deps-update/
+/ebin/
+/ejabberd.init
+/ejabberd.service
+/ejabberdctl
+/ejabberdctl.example
+/rel/ejabberd/
+/rel/overlays/
+/src/eldap_filter_yecc.erl
+/vars.config
+/dialyzer/
+/test/*.beam
+/test/*.ctc
+/logs/
+/priv/bin/captcha*sh
+/priv/sql
+/rel/ejabberd
+/_build
+/database/
+/.rebar
+/rebar.lock
+/log/
+Mnesia.nonode@nohost/
+# Binaries created with tools/make-{binaries,installers,packages}:
+/ejabberd_*.deb
+/ejabberd-*.rpm
+/ejabberd-*.run
+/ejabberd-*.tar.gz
+
diff --git a/.github/container/Dockerfile b/.github/container/Dockerfile
index a879a125d..0601a2e5c 100644
--- a/.github/container/Dockerfile
+++ b/.github/container/Dockerfile
@@ -1,5 +1,4 @@
 FROM alpine:3.15.4 AS build
-ARG REPOSITORY=https://github.com/processone/ejabberd.git
 ARG VERSION=master
 
 RUN apk upgrade --update musl \
@@ -29,11 +28,11 @@ RUN apk upgrade --update musl \
 RUN mix local.hex --force \
     && mix local.rebar --force
 
+COPY . ./ejabberd
+
 WORKDIR ejabberd
 
-RUN git clone $REPOSITORY . \
-    && git checkout $VERSION \
-    && mv .github/container/ejabberdctl.template . \
+RUN mv .github/container/ejabberdctl.template . \
     && ./autogen.sh \
     && ./configure --with-rebar=mix --enable-all \
     && make deps \
@@ -44,7 +43,6 @@ RUN cp -r _build/prod/rel/ejabberd/ /opt/ejabberd-$VERSION \
     && mv /opt/ejabberd-$VERSION/conf /opt/ejabberd/conf
 
 RUN BINPATH=$(dirname $(find /opt -name msgs))/bin/ \
-    && mkdir $BINPATH \
     && cp tools/captcha*.sh $BINPATH
 
 RUN export PEM=/opt/ejabberd/conf/server.pem \
diff --git a/.github/workflows/container.yml b/.github/workflows/container.yml
index 7256058e5..105d14abb 100644
--- a/.github/workflows/container.yml
+++ b/.github/workflows/container.yml
@@ -58,11 +58,11 @@ jobs:
         uses: docker/build-push-action@v2.10.0
         with:
           build-args: |
-            REPOSITORY=https://github.com/${{ github.repository }}.git
             VERSION=${{ steps.gitdescribe.outputs.ver }}
           cache-from: type=gha
           cache-to: type=gha,mode=max
-          context: .github/container
+          context: .
+          file: .github/container/Dockerfile
           labels: ${{ steps.meta.outputs.labels }}
           platforms: linux/amd64,linux/arm64
           push: true
```

</details>

**Comment by RomanHargrave** [comment]
Your version of the patch looks good, and I'll test it. I don't have any personal preference for the location of the Dockerfile, though I will say that having it in`/` makes it more obvious to newcomers. Regarding the batch file, it certainly is not technically part of the change, but I could not find it referenced anywhere or used in producing an artifact - being buried in a tooling folder, I can't imagine it's readily discovered.

**Comment by badlop** [comment]
Thanks, merged!

Right, the Windows batch file is not used here, it's mentioned in the corresponding tutorial, linked in the Downloads webpage.

**Comment by badlop** [comment]
Ok, I've applied some minor changes to the Dockerfile.

BTW, can you take a look at https://github.com/processone/ejabberd/pull/3832? Specifically to the change it introduces in the container image. Would that feature help to administer the containers, or would it introduce problems instead?

**Pull request merged**
