### PR TITLE
mod_mix: Use disco identity conference/mix

### LINKED ISSUE #2901: MIX Service has wrong type in disco identity
```
<iq xml:lang="de" to="xxx@messaging.one/kaidan.MGfj" from="group.messaging.one" type="result" id="qxmpp16" xmlns="http://jabber.org/protocol/disco#info">
    <query>
        <identity name="Channels" type="text" category="conference"/>
        <feature var="http://jabber.org/protocol/disco#info"/>
        <feature var="http://jabber.org/protocol/disco#items"/>
        <feature var="urn:xmpp:mix:core:0"/>
        <feature var="urn:xmpp:mix:core:0#searchable"/>
        <feature var="urn:xmpp:mix:core:0#create-channel"/>
        <x xmlns="jabber:x:data" type="result">
            <field var="FORM_TYPE" type="hidden">
                <value>http://jabber.org/network/serverinfo</value>
            </field>
            <field var="abuse-addresses" type="list-multi">
                <value>mailto:abuse@messaging.one</value>
            </field>
            <field var="admin-addresses" type="list-multi">
                <value>mailto:abuse@messaging.one</value>
            </field>
            <field var="support-addresses" type="list-multi">
                <value>mailto:abuse@messaging.one</value>
            </field>
        </x>
    </query>
</iq>
```

The identity is wrong:
```
        <identity name="Channels" type="text" category="conference"/>
```

It should be:
```
        <identity name="Channels" type="mix" category="conference"/>
```

See the XEP for details: https://xmpp.org/extensions/xep-0369.html#example-5

### PR DESCRIPTION
**Pull request by lnjX**
Probably someone has forgotten to update it here.
https://xmpp.org/extensions/xep-0369.html#example-5

Fixes #2901.

### CODE REVIEW

**Comment by badlop** [comment]
Hi!

mod_mix.erl is said to implement XEP-0369 version 1.13.0

https://github.com/processone/ejabberd/blob/e3e4dae58394446189beeb782852c31f24a6976a/src/mod_mix.erl#L27

so the reference document to look at is this one: https://xmpp.org/extensions/attic/xep-0369-0.13.0.html

Looking at that closely, [example 5](https://xmpp.org/extensions/attic/xep-0369-0.13.0.html#example-5) and [example 31](https://xmpp.org/extensions/attic/xep-0369-0.13.0.html#example-31) show that the MIX service is of `type='text'`:

```xml
    <identity
        category='conference'
        name='Shakespearean Chat Service'
        type='text'/>
```

On the other hand, [example 9](https://xmpp.org/extensions/attic/xep-0369-0.13.0.html#example-9) shows that a MIX channel is of `type='mix'`:

```xml
    <identity
        category='conference'
        name='A Dark Cave'
        type='mix'/>
```

And in more recent times, as you noticed, [example 5](https://xmpp.org/extensions/xep-0369.html#example-5) and 31 have changed in 0.14.0, but ejabberd does not implement that version... or maybe it does?

**Comment by lnjX** [comment]
Okay, you're right 0.13.0 actually still uses `type='text'`, but I guess that this was a XEP author's mistake as it makes not much sense to have `type='text'` for the component and `type='mix'` for the channel. Anyway for 1.13.0 the current way is the standards-conform way, but the change is need of course for updating to v1.14.

If you're or processone is concerned about backwards compatibility we could add the new identity with `type='mix'` additionally to the `type='text'` identity, but in general it would be helpful to drop the support of the old versions to keep the code clean. The module description says that mod_mix is in an experimental state so I guess that should be possible?

**Comment by lnjX** [comment]
Ah and mod_mix currently supports requesting the MIX channels via `disco#items` with `node='mix'` and without, but the node parameter was only removed in 0.14.0, so the current implementation already is 0.13 + parts of 0.14.
https://github.com/processone/ejabberd/blob/e3e4dae58394446189beeb782852c31f24a6976a/src/mod_mix.erl#L221-L223

**Comment by badlop** [comment]
Ok, I also checked the changes between 1.13.0 and 0.14.1 in https://github.com/xsf/xeps with `git diff 5854c8d5..b48dea84 xep-0369.xml`... nothing substantial.

It seems mod_mix supports 0.14.1, except requiring nick when joining a channel, and retracting an item.

So I guess your PR can be applied, and consider that the version supported is 1.14.1.

**Comment by Neustradamus** [comment]
To look easily:
- 0.13.0 to 0.14.0: http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0369-0.13.0.html&newfile=https://xmpp.org/extensions/attic/xep-0369-0.14.0.html
- 0.13.0 to 0.14.1: http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0369-0.13.0.html&newfile=https://xmpp.org/extensions/attic/xep-0369-0.14.1.html
- 0.13.0 to 0.14.2: http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0369-0.13.0.html&newfile=https://xmpp.org/extensions/attic/xep-0369-0.14.2.html
- 0.13.0 to 0.14.3: http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0369-0.13.0.html&newfile=https://xmpp.org/extensions/attic/xep-0369-0.14.3.html
- 0.13.0 to 0.14.4: http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0369-0.13.0.html&newfile=https://xmpp.org/extensions/attic/xep-0369-0.14.4.html
- 0.13.0 to 0.14.5: http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0369-0.13.0.html&newfile=https://xmpp.org/extensions/attic/xep-0369-0.14.5.html
- 0.13.0 to 0.14.6: http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0369-0.13.0.html&newfile=https://xmpp.org/extensions/attic/xep-0369-0.14.6.html

**Pull request merged**
