### PR TITLE
ldap_shared_cache: caching groups for host

### PR DESCRIPTION
**Pull request by annmuor**
This patch is very helpful for ejabberd which connectet to LDAP server with hundreds of groups.
It avoids getting groups list from LDAP on every user connection.

### CODE REVIEW

**Comment by sharewax** [comment]
This pull request is not actual since 16.02

**Comment by Neustradamus** [comment]
@annmuor: Can you sign the CLA?

**Comment by annmuor** [comment]
> @annmuor: Can you sign the CLA?

Fix your bots please, I've done this a year ago.

**Comment by Neustradamus** [comment]
@mremond: Can you remove the "cla-missing" and look the bot problems?
Thanks in advance.

**Comment by Neustradamus** [comment]
@processone, @mremond: @annmuor has signed, can you remove the "cla-missing" and look the bot problems?

Thanks in advance.

**Comment by Neustradamus** [comment]
@annmuor: Another guy has signed the CLA today (a big LDAP feature), the bot works.
Maybe you can only validate a new time, it is easy and there will be no problem if you have already done it...
- https://cla.process-one.net/

I really would like that your PR to be merged.

Thanks in advance.

**Comment by Neustradamus** [comment]
@annmuor: Can you look the CLA?
Please check the status, after "Sign in with GitHub", you must to see the state of your sign.

**Comment by annmuor** [comment]
@Neustradamus [
2021-01-20-170345_712x455_scrot
](url)

**Comment by Neustradamus** [comment]
@annmuor: Thanks for your reply!

Have you validated the links into "ProcessOne CLA" email received?

When all steps are finished, you must have:
- Status "completed"

Maybe you can do a reset...

@badlop: What do you think?

**Comment by Neustradamus** [comment]
@annmuor: Nice, now it is good, never to late :)
You can remove your screenshot ^^

Have you possibility to rebase?

I hope that it can be merged before next build and to have in Debian 11.

**Comment by prefiks** [comment]
Hello,

I commited 8c5b312601ce842a073f023fa7b08798f9c25be6, that adapts it to new cache infrastructure and also add user to cache key.

**Comment by badlop** [comment]
Supposedly, that commit implements the feature, and this PR would not be needed.

**Comment by prefiks** [comment]
Yes, that's true, i just forgot to close it.

**Pull request closed without merging**
