### PR TITLE
fixing mix compile with ejabberd as dep

### PR DESCRIPTION
**Pull request by IRog**
`mix deps.compile ejabberd` was failing prior to this change. I tested it with the following mix file and doing `mix do deps.get, compile` from within the mix project:

```elixir
defmodule Ejapp.Mixfile do
  use Mix.Project

  def project do
    [app: :ejapp,
     version: "0.1.0",
     elixir: "~> 1.4",
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps()]
  end

  def application do
    [extra_applications: [:logger, :ejabberd]]
  end

  defp deps do
    [{:ejabberd, git: "https://github.com/IRog/ejabberd.git", branch: "fixMixBuild"}]
  end
end

```

Without this change using ejabberd as an Elixir mix dependency seems to be broken and "Embedding ejabberd in an Elixir application" in https://docs.ejabberd.im/developer/extending-ejabberd/elixir/ wasn't working also addressing https://github.com/processone/ejabberd/issues/1774

### CODE REVIEW

**Comment by jglover** [comment]
Using this branch in deps, using the following mix file
```
def project do
    [
      app: :my_app,
      version: "0.0.1",
      elixir: "~> 1.4",
      elixirc_paths: elixirc_paths(Mix.env),
      compilers: [:phoenix, :gettext] ++ Mix.compilers,
      build_embedded: Mix.env == :prod,
      start_permanent: Mix.env == :prod,
      aliases: aliases(),
      deps: deps(),
    ]
  end
...
    [mod: {MyApp, []},
     applications: [:phoenix, :phoenix_pubsub, :phoenix_html, :cowboy, :logger, :gettext,
                    :phoenix_ecto, :postgrex, :comeonin, :ex_aws, :hackney, :poison, :ex_twilio, :ejabberd]]
  end
...
defp deps do
    [{:phoenix, "~> 1.2.1"},
     {:phoenix_pubsub, "~> 1.0"},
     {:phoenix_ecto, "~> 3.0"},
     {:postgrex, ">= 0.10.0"},
     ...
     {:ejabberd, git: "https://github.com/IRog/ejabberd.git", branch: "fixMixBuild"}]
end
```

 I get 
```
** (Mix) Could not start application ejabberd: exited in: :ejabberd_app.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function :ejabberd_app.start/2 is undefined (module :ejabberd_app is not available)
            :ejabberd_app.start(:normal, [])
            (kernel) application_master.erl:273: :application_master.start_it_old/4
```

**Comment by IRog** [comment]
I'm looking at your issue, but would still like this merged in, as it still fixes the compile problem...

**Comment by jglover** [comment]
@IRog agree, getting this merged would at least allow for development.

**Comment by jglover** [comment]
So I'm confused by this, `deps/ejabberd/src/ejabberd_app.erl` exists, it defines and exports the right things. I'm using your mix file in a new project, but still getting the same error.
 First few lines of `ejabberd_app.erl`:
```erlang
-module(ejabberd_app).

-behaviour(ejabberd_config).
-author('alexey@process-one.net').

-behaviour(application).

-export([start/2, prep_stop/1, stop/1, opt_type/1]).
```

**Comment by IRog** [comment]
The Elixir compiler doesn't seem to pickup the erlang modules compiled by the `mix compile.erlang` task. I was going to play with output directories for that task to see where iex/Elixir looks for the beam files or some such but don't have the time atm. (I might also try another solution)

**Comment by jglover** [comment]
`fast_tls` dependency seems to be broken again and causing ejabberd to fail.
On a fresh Elixir project using only ejabberd as a dependency anything =< 17.03 won't compile due to SemVer (fixed in #1759) and 17.06 compiles but encounters fast_tls issues when run using `iex -S mix`. This includes using the docker container `processone/mix` (w/ Elixir/Mix upgraded to 1.4).

I don't mean to sound negative but the hex packages are just not very usable right now. I understand Elixir support is new though and there are other priorities.
If there's anything helpful I can do to assist please let me know @badlop

**Comment by IRog** [comment]
I created https://github.com/processone/fast_tls/issues/22 for the fast_tls issue and updated my PR with some slight changes. I'm raising the modules min versions to fix some dependency resolution issues I ran into and fixing some compiler warnings. Will still blow-up on attempted usage due to fast_tls issue.

**Comment by IRog** [comment]
@jglover Use my https://github.com/IRog/ejabberd/tree/workingIex for a working version. In addition to fast_tls, xmpp, and cache_tab have the same issues and are missing some files (/priv/lib/*.so) in the elixir module published on hex. @badlop

**Comment by jglover** [comment]
Hey @IRog, just tried and I can't compile using your branch. Was there anything else required to compile? I used a new mix project, added your fork/branch as a single dependency:  
`{:ejabberd, github: "IRog/ejabberd", branch: "workingIex"}`

**Comment by IRog** [comment]
It was working locally with being set as `{:ejabberd, path: "../../forked-ejabberd/ejabberd"}` I'll check later tonight.

**Comment by johnhamelink** [comment]
@IRog did you ever get the chance to double check this? I have tried using `{:ejabberd, github: "IRog/ejabberd", branch: "workingIex"}`, and while it compiles fine, it does not boot:

```
[john:~/Public/fap/api/2.1] hotfix/upgrade-ejabberd(+29/-38)+ 4s 1 ± iex -S mix phoenix.server
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

===> Compiling fast_xml
[info] Starting Mailchimp Application
[info] Application ejabberd exited: exited in: :ejabberd_app.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function :ejabberd_app.start/2 is undefined (module :ejabberd_app is not available)
            :ejabberd_app.start(:normal, [])
            (kernel) application_master.erl:273: :application_master.start_it_old/4
[info] Application ex_statsd exited: :stopped
[info] Application elibphonenumber exited: :stopped
[info] Application phoenix_ecto exited: :stopped
[info] Application cowboy exited: :stopped
[info] Application cowlib exited: :stopped
[info] Application ranch exited: :stopped
[info] Application phoenix_html exited: :stopped
** (Mix) Could not start application ejabberd: exited in: :ejabberd_app.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function :ejabberd_app.start/2 is undefined (module :ejabberd_app is not available)
            :ejabberd_app.start(:normal, [])
            (kernel) application_master.erl:273: :application_master.start_it_old/4
```

**Comment by IRog** [comment]
So I think there may be a bug in Elixir dependency resolution for third party modules in regards to custom compilers, but I'm still not sure. The current workaround is to download my fork `https://github.com/IRog/ejabberd/tree/fixIex` to your filesystem then point to it as your dependency in your mix file `{:ejabberd, path: "../ejabberd"}` if you follow the other steps in https://docs.ejabberd.im/developer/extending-ejabberd/elixir/ this will let you `iex -S mix` with ejabberd starting as a dependency. I think I'm going to open an issue about mix for Elixir core. Just have the above workaround for now :( @johnhamelink @jglover

**Comment by johnhamelink** [comment]
@IRog thanks for this info, but it's not working for me I'm afraid:

I'm using an umbrella app, and the dependency is inside one of the apps (`api` is the name of it), so for me the path to link to the dependency is: `{:ejabberd, path: "../../../ejabberd"}`.

When I run `mix do deps.get, compile`, I get the following output: https://gist.github.com/johnhamelink/71a680d581807f20f44e16944fb5dc9b

To me, it looks like Elixir can't find the .hrl files (for example: `src/ejabberd_c2s.erl:55: can't find include file "xmpp.hrl"`).

I'm guessing this is because I have an umbrella app.

**Comment by leeicmobile** [comment]
I exteneded and made a simlilar fork to yourself @IRog which sorted the umbrella include issue for me.
`defp erlc_options do
    # Use our own includes + includes from all dependencies
    if Mix.Project.umbrella? do 
      [:debug_info, {:d, :ELIXIR_ENABLED}, {:i, "../../deps/fast_xml/include"}, {:i, "../../deps/p1_utils/include"}, {:i, "../../deps/xmpp/include"}]
    else
      [:debug_info, {:d, :ELIXIR_ENABLED}, {:i, "deps/fast_xml/include"}, {:i, "deps/p1_utils/include"}, {:i, "deps/xmpp/include"}]
    end
  end`

**Comment by cromain** [comment]
i don't get what's wrong with current deps_include function.
it works for me without problems, have ejabberd as a mix deps, and ejabberd can build thanks to deps_include choosing the right path

**Comment by leeicmobile** [comment]
@cromain what's your current projects structure?

Ours is 
- Umbrella App
 - DB APP
  - API App
     - Ejabberd

If we where to build API App with mix deps e.t.c then yes deps_include would be sufficient, it doesn't appear to work for building from the umbrella app level.

**Pull request closed without merging**
