### PR TITLE
option to prevent archive removal on room destroy

### PR DESCRIPTION
**Pull request by ChaosKid42**
I'd like to keep the message archive even after a room is destroyed. Therefore I propose a new option of mod_mam `clear_archive_on_room_destroy` which defaults to `true`.

As this can lead to privacy issues (see weiss' comment below) I implemented a check, that disallows room creation if the archive for this newly created room is not empty. To be backwards compatible this check will only be performed if `clear_archive_on_room_destroy` is `false`.

My use-case is as follows: I'm mainly using private, persistent rooms. The archive is cleaned by regularily calling `ejabberdctl delete_old_messages <days>`. Rooms may be created and destroyed by users but I'd like to keep the room's message archives (until they are deleted by the above command) for reasons of accountability even if a user decides to destroy a room.

This PR also adds two new commands `ejabberdctl rooms_empty_list <Server>`  and `ejabberdctl rooms_empty_destroy <Server>` which allow to list and destroy rooms that have an empty archive.

I will happily write an entry for the documentation if my PR is accepted.

### CODE REVIEW

**Comment by weiss** [comment]
This is hairy.  If, after room destruction, another user creates a room of the same name, he'll get access to the archive which may well have been restricted to the old room's members before.  I'd certainly not do this by default.

**Comment by ChaosKid42** [comment]
@weiss: Right. That's why it's `true` by default. I will point out the risk of setting it to `false` in the documentation.

**Comment by ChaosKid42** [comment]
@weiss: Maybe a check, that would reject room creation for rooms that still have archived contents would do. What do you think?
That would be similar to a tombstone.
Unfortunately I don't know enough erlang to do it...

**Comment by weiss** [comment]
> I'd like to keep the room's message archives (until they are deleted by the above command) for reasons of accountability

Wouldn't it make sense to also add an such an option for user archives, by the way?  Except that this potentially introduces the same issue if a deleted account name is reused by someone else.  But maybe we could argue that this kind of account management issues are within the admin's realm.

**Comment by ChaosKid42** [comment]
@weiss: Thanks for your advice. Maybe I'll find some time tonight to implement the changes.

**Comment by ChaosKid42** [comment]
@weiss I believe I implemented the changes you suggested. What do you think?

**Pull request merged**
