### PR TITLE
use dsn-less config for mssql

### PR DESCRIPTION
**Pull request by ChaosKid42**
Using dsn-less config with FreeTDS (https://www.freetds.org/userguide/dsnless.htm) can simplify the setup of mssql a lot.

### CODE REVIEW

**Comment by Neustradamus** [comment]
@mremond: Do not forget this PR :)

**Comment by weiss** [comment]
@Neustradamus, you've been asked to stop spamming issue trackers by countless people, countless times. I doubt there's any developer in the XMPP community who has _not_ yet tried to explain that telling people to work faster doesn't make people work faster as long as you're neither their boss nor their customer. If anything it will yield the opposite result because people become annoyed of your entitlement mentality. Each of those comments triggers totally useless, distracting notifications to all subscribers, they make it harder to read the discussion, and they add no value at all.

Is there really absolutely no way to make you stop this behavior? You'll just continue to ignore all developers asking you to change it, and blindly continue no matter what?

**Comment by licaon-kter** [comment]
With enough complains maybe Github will take notice.

**Comment by Neustradamus** [comment]
@weiss: The message was not for you, it is only because it is @mremond have looked for other MSSQL PRs: https://github.com/processone/ejabberd/commits?author=ChaosKid42
And it was published one day after, I think many oversights :)

**Comment by mremond** [comment]
@weiss is right. Open Source contributions are based on people taking pleasure on working on project. The more you post things like this, the less people are likely to listen to you or try to help you.
You are not making a favor to yourself or the community doing so, because you are sending a very bad signal to developer dedicating their time to make the project better.

**Comment by prefiks** [comment]
I am unable to test this, as i don't have mssql server available that i can use to test it, but looking at this document it seems to be correct. Let's merge it then.

**Comment by ChaosKid42** [comment]
@prefiks Thanks.
btw. That's how I usually test against SQLServer:

```
docker run --name mssql -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=SAPass4321!' -p 1433:1433 -v sqlvolume:/var/opt/mssql -d mcr.microsoft.com/mssql/server

docker exec -it mssql /opt/mssql-tools/bin/sqlcmd -U sa -P SAPass4321 -S localhost

CREATE DATABASE ejabberd;
GO

USE ejabberd;
GO

CREATE LOGIN ejabberd WITH PASSWORD = 'ejabberdPass';  
GO

CREATE USER ejabberd FOR LOGIN ejabberd;
GO

GRANT ALL TO ejabberd;
GO

GRANT CONTROL ON SCHEMA ::dbo TO ejabberd;
GO

docker cp mssql.sql mssql:/
docker exec -it mssql /opt/mssql-tools/bin/sqlcmd -U ejabberd -P ejabberdPass -S localhost -d ejabberd -i /mssql.sql
```

So no need to actually go into installing SQLServer if you have docker running on your local machine.

**Pull request merged**
