### PR TITLE
add mongodb dependency to configure/rebar

### PR DESCRIPTION
**Pull request by nhuancreativ**
Mod mam

### CODE REVIEW

**Comment by mremond** [comment]
I think that Mongo mod_mam should go in ejabberd-contrib repository.

**Comment by weiss** [comment]
@nhuancreativ, did you try the Mnesia-based `mod_mam` which is already [in the ejabberd-contrib repository][1], by the way?  Or is Mnesia not an option for you?

(Though note that the MongoDB-based module currently supports only version 0.2 of the MAM specification, while the module in ejabberd-contrib supports only version 0.3.)

[1]: https://github.com/processone/ejabberd-contrib/tree/master/mod_mam

**Comment by mremond** [comment]
We have no plan to include mongogb support inside the main ejabberd core as for nosql we are focused on Riak for a few month.

Maybe a joint effort around the mod_mam in ejabberd contrib is the way to go ?

**Comment by Neustradamus** [comment]
@ghost Have you found a solution for MongoDB?
- https://github.com/deolan/ejabberd-mongodb-driver
- https://github.com/kongo2002/ejabberd-mod-mam
- https://github.com/comtihon/mongodb-erlang

@mremond, @weiss: possibility to see for add the driver and mam in ejabberd-contrib?

Linked to:
- https://github.com/processone/ejabberd/issues/419
- https://github.com/processone/ejabberd/issues/305

**Pull request closed without merging**
