### PR TITLE
Add process hook tracing

### PR DESCRIPTION
**Pull request by pouriya**
- This implementation has the minimum overhead for normal situations. (The only overhead is [here](https://github.com/processone/ejabberd/compare/master...pouriya:Add-Process-Hook-Tracing?expand=1#diff-42a9ab1d58ab50ab716ce010d785b4469c70abdbfdcad75a954ecafae7ad0ae6R118))  
- I tried to keep original implemetation untouched.  
- Supports implementing new event handlers for hook tracing.  
- For now, just a simple `timing` event handler is implemented. I'm planning to add another event handler that shows accumulator changes in `ejabberd_hooks:run_fold`.

# Examples for timing event handler
#### Tracing one hook for one host
<details>

```erlang
02:51:52.151 [info] (<0.558.0>) Accepted connection 127.0.0.1:40074 -> 127.0.0.1:5222
02:51:58.177 [info] (tcp|<0.558.0>) Accepted c2s PLAIN authentication for test1@bmp-develop.phoenix.mahsan.net by http backend from 127.0.0.1
02:51:58.988 [info] (tcp|<0.558.0>) Opened c2s session for test1@bmp-develop.phoenix.mahsan.net/CodeFather

(ejabberd@localhost)1> HookName = c2s_terminated,
(ejabberd@localhost)1> Host = <<"bmp-develop.phoenix.mahsan.net">>,
(ejabberd@localhost)1> TracePid = <0.558.0>,
(ejabberd@localhost)1> TraceOpts = #{},
(ejabberd@localhost)1> TraceTime = undefined,
(ejabberd@localhost)1> ok.
ok
(ejabberd@localhost)2> ejabberd_hooks:trace_on(HookName, Host, TracePid, TraceOpts, TraceTime).
ok

(ejabberd@localhost)3> % Disconnect the user

(ejabberd@localhost)3> 02:53:23.207 [info] (c2s_terminated|bmp-develop.phoenix.mahsan.net) Timing started
02:53:28.129 [info] (c2s_terminated|bmp-develop.phoenix.mahsan.net) mod_pubsub:on_user_offline/2 got 4922052936ns
02:53:28.129 [info] (tcp|<0.558.0>) Closing c2s session for test1@bmp-develop.phoenix.mahsan.net/CodeFather: Connection failed: connection closed
02:53:28.230 [info] (c2s_terminated|bmp-develop.phoenix.mahsan.net) ejabberd_c2s:process_terminated/2 got 101279765ns
02:53:28.231 [info] (c2s_terminated|bmp-develop.phoenix.mahsan.net) All callbacks got 5023332701ns to run. Sorted running time:
        ejabberd_c2s:process_terminated/2 -> 101279765ns
        mod_pubsub:on_user_offline/2 -> 4922052936ns
02:53:28.231 [info] (c2s_terminated|bmp-develop.phoenix.mahsan.net) Time calculations for all callbacks got 634396ns
02:53:28.231 [info] (c2s_terminated|bmp-develop.phoenix.mahsan.net) Timing stopped
```
</details>

#### Tracing all hooks for all hosts
<details>

```erlang
02:54:26.734 [info] (<0.558.0>) Accepted connection 127.0.0.1:40086 -> 127.0.0.1:5222
02:54:33.214 [info] (tcp|<0.558.0>) Accepted c2s PLAIN authentication for test1@bmp-develop.phoenix.mahsan.net by http backend from 127.0.0.1
02:54:33.906 [info] (tcp|<0.558.0>) Opened c2s session for test1@bmp-develop.phoenix.mahsan.net/CodeFather

(ejabberd@localhost)1> AllHooks = '_',
(ejabberd@localhost)1> AllHosts = <<"*">>,
(ejabberd@localhost)1> TracePid = <0.558.0>,
(ejabberd@localhost)1> TraceOpts = #{},
(ejabberd@localhost)1> TraceTime = undefined,
(ejabberd@localhost)1> ok.
ok
(ejabberd@localhost)2> ejabberd_hooks:trace_on(AllHooks, AllHosts, TracePid, TraceOpts, TraceTime).
ok

(ejabberd@localhost)3> % Disconnect the user

(ejabberd@localhost)3> 02:55:25.770 [info] (c2s_handle_recv|bmp-develop.phoenix.mahsan.net) Timing started
02:55:25.772 [info] (c2s_handle_recv|bmp-develop.phoenix.mahsan.net) ejabberd_tcp_trace_user:received_element/3 got 76692ns
02:55:25.772 [info] (c2s_handle_recv|bmp-develop.phoenix.mahsan.net) Timing stopped
02:55:25.772 [info] (user_send_packet|bmp-develop.phoenix.mahsan.net) Timing started
02:55:25.772 [info] (user_send_packet|bmp-develop.phoenix.mahsan.net) mod_conversation:user_send_packet/1 got 12407ns
02:55:25.773 [info] (user_send_packet|bmp-develop.phoenix.mahsan.net) mod_privacy:user_send_packet/1 got 11554ns
02:55:25.773 [info] (user_send_packet|bmp-develop.phoenix.mahsan.net) mod_vcard_xupdate:user_send_packet/1 got 10209ns
02:55:25.773 [info] (user_send_packet|bmp-develop.phoenix.mahsan.net) mod_caps:user_send_packet/1 got 10449ns
02:55:25.773 [info] (user_send_packet|bmp-develop.phoenix.mahsan.net) mod_mam:user_send_packet/1 got 12707ns
02:55:25.774 [info] (user_send_packet|bmp-develop.phoenix.mahsan.net) mod_carboncopy:user_send_packet/1 got 12768ns
02:55:25.774 [info] (user_send_packet|bmp-develop.phoenix.mahsan.net) mod_mam:user_send_packet_strip_tag/1 got 10694ns
02:55:25.774 [info] (user_send_packet|bmp-develop.phoenix.mahsan.net) All callbacks got 80788ns to run. Sorted running time:
        mod_vcard_xupdate:user_send_packet/1 -> 10209ns
        mod_caps:user_send_packet/1 -> 10449ns
        mod_mam:user_send_packet_strip_tag/1 -> 10694ns
        mod_privacy:user_send_packet/1 -> 11554ns
        mod_conversation:user_send_packet/1 -> 12407ns
        mod_mam:user_send_packet/1 -> 12707ns
        mod_carboncopy:user_send_packet/1 -> 12768ns
02:55:25.774 [info] (user_send_packet|bmp-develop.phoenix.mahsan.net) Time calculations for all callbacks got 1548973ns
02:55:25.774 [info] (user_send_packet|bmp-develop.phoenix.mahsan.net) Timing stopped
02:55:25.775 [info] (unset_presence_hook|bmp-develop.phoenix.mahsan.net) Timing started
02:55:26.212 [info] (unset_presence_hook|bmp-develop.phoenix.mahsan.net) mod_last:on_presence_update/4 got 437259554ns
02:55:26.212 [info] (unset_presence_hook|bmp-develop.phoenix.mahsan.net) Timing stopped
02:55:26.212 [info] (c2s_self_presence|bmp-develop.phoenix.mahsan.net) Timing started
02:55:26.213 [info] (c2s_self_presence|bmp-develop.phoenix.mahsan.net) mod_offline:c2s_self_presence/1 got 11781ns
02:55:26.213 [info] (c2s_self_presence|bmp-develop.phoenix.mahsan.net) mod_roster:c2s_self_presence/1 got 10757ns
02:55:26.213 [info] (c2s_self_presence|bmp-develop.phoenix.mahsan.net) mod_pubsub:on_self_presence/1 got 8992ns
02:55:26.213 [info] (c2s_self_presence|bmp-develop.phoenix.mahsan.net) mod_vcard_xupdate:update_presence/1 got 8461ns
02:55:26.213 [info] (c2s_self_presence|bmp-develop.phoenix.mahsan.net) All callbacks got 39991ns to run. Sorted running time:
        mod_vcard_xupdate:update_presence/1 -> 8461ns
        mod_pubsub:on_self_presence/1 -> 8992ns
        mod_roster:c2s_self_presence/1 -> 10757ns
        mod_offline:c2s_self_presence/1 -> 11781ns
02:55:26.213 [info] (c2s_self_presence|bmp-develop.phoenix.mahsan.net) Time calculations for all callbacks got 557618ns
02:55:26.213 [info] (c2s_self_presence|bmp-develop.phoenix.mahsan.net) Timing stopped
02:55:26.213 [info] (roster_get|bmp-develop.phoenix.mahsan.net) Timing started
02:55:27.076 [info] (roster_get|bmp-develop.phoenix.mahsan.net) mod_roster:get_user_roster/2 got 861909675ns
02:55:27.503 [info] (roster_get|bmp-develop.phoenix.mahsan.net) mod_auth_backend_roster:get_roster/2 got 426844636ns
02:55:27.503 [info] (roster_get|bmp-develop.phoenix.mahsan.net) All callbacks got 1288754311ns to run. Sorted running time:
        mod_auth_backend_roster:get_roster/2 -> 426844636ns
        mod_roster:get_user_roster/2 -> 861909675ns
02:55:27.503 [info] (roster_get|bmp-develop.phoenix.mahsan.net) Time calculations for all callbacks got 526520ns
02:55:27.503 [info] (roster_get|bmp-develop.phoenix.mahsan.net) Timing stopped
02:55:27.503 [info] (privacy_check_packet|bmp-develop.phoenix.mahsan.net) Timing started
02:55:27.504 [info] (privacy_check_packet|bmp-develop.phoenix.mahsan.net) mod_last:privacy_check_packet/4 got 18311ns
02:55:27.504 [info] (privacy_check_packet|bmp-develop.phoenix.mahsan.net) mod_privacy:check_packet/4 got 66547ns
02:55:27.504 [info] (privacy_check_packet|bmp-develop.phoenix.mahsan.net) All callbacks got 84858ns to run. Sorted running time:
        mod_last:privacy_check_packet/4 -> 18311ns
        mod_privacy:check_packet/4 -> 66547ns
02:55:27.504 [info] (privacy_check_packet|bmp-develop.phoenix.mahsan.net) Time calculations for all callbacks got 507321ns
02:55:27.505 [info] (privacy_check_packet|bmp-develop.phoenix.mahsan.net) Timing stopped
02:55:27.505 [info] (privacy_check_packet|bmp-develop.phoenix.mahsan.net) Timing started
02:55:27.505 [info] (privacy_check_packet|bmp-develop.phoenix.mahsan.net) mod_last:privacy_check_packet/4 got 13744ns
02:55:27.505 [info] (privacy_check_packet|bmp-develop.phoenix.mahsan.net) mod_privacy:check_packet/4 got 51061ns
02:55:27.505 [info] (privacy_check_packet|bmp-develop.phoenix.mahsan.net) All callbacks got 64805ns to run. Sorted running time:
        mod_last:privacy_check_packet/4 -> 13744ns
        mod_privacy:check_packet/4 -> 51061ns
02:55:27.505 [info] (privacy_check_packet|bmp-develop.phoenix.mahsan.net) Time calculations for all callbacks got 420328ns
02:55:27.506 [info] (privacy_check_packet|bmp-develop.phoenix.mahsan.net) Timing stopped
02:55:27.506 [info] (privacy_check_packet|bmp-develop.phoenix.mahsan.net) Timing started
02:55:27.506 [info] (privacy_check_packet|bmp-develop.phoenix.mahsan.net) mod_last:privacy_check_packet/4 got 12256ns
02:55:27.506 [info] (privacy_check_packet|bmp-develop.phoenix.mahsan.net) mod_privacy:check_packet/4 got 45190ns
02:55:27.506 [info] (privacy_check_packet|bmp-develop.phoenix.mahsan.net) All callbacks got 57446ns to run. Sorted running time:
        mod_last:privacy_check_packet/4 -> 12256ns
        mod_privacy:check_packet/4 -> 45190ns
02:55:27.507 [info] (privacy_check_packet|bmp-develop.phoenix.mahsan.net) Time calculations for all callbacks got 455304ns
02:55:27.507 [info] (privacy_check_packet|bmp-develop.phoenix.mahsan.net) Timing stopped
02:55:27.507 [info] (sm_receive_packet|bmp-develop.phoenix.mahsan.net) Timing started
02:55:27.507 [info] (sm_receive_packet|bmp-develop.phoenix.mahsan.net) mod_mam:sm_receive_packet/1 got 14822ns
02:55:27.507 [info] (sm_receive_packet|bmp-develop.phoenix.mahsan.net) Timing stopped
02:55:27.507 [info] (sm_receive_packet|bmp-develop.phoenix.mahsan.net) Timing started
02:55:27.508 [info] (sm_receive_packet|bmp-develop.phoenix.mahsan.net) mod_mam:sm_receive_packet/1 got 13208ns
02:55:27.508 [info] (sm_receive_packet|bmp-develop.phoenix.mahsan.net) Timing stopped
02:55:27.508 [info] (sm_receive_packet|bmp-develop.phoenix.mahsan.net) Timing started
02:55:27.508 [info] (sm_receive_packet|bmp-develop.phoenix.mahsan.net) mod_mam:sm_receive_packet/1 got 13645ns
02:55:27.508 [info] (sm_receive_packet|bmp-develop.phoenix.mahsan.net) Timing stopped
02:55:27.509 [info] (c2s_closed|bmp-develop.phoenix.mahsan.net) Timing started
02:55:27.509 [info] (c2s_closed|bmp-develop.phoenix.mahsan.net) ejabberd_c2s:process_closed/2 got 23452ns
02:55:27.509 [info] (c2s_closed|bmp-develop.phoenix.mahsan.net) Timing stopped
02:55:27.509 [info] (c2s_terminated|bmp-develop.phoenix.mahsan.net) Timing started
02:55:32.587 [info] (c2s_terminated|bmp-develop.phoenix.mahsan.net) mod_pubsub:on_user_offline/2 got 5077725057ns
02:55:32.587 [info] (tcp|<0.558.0>) Closing c2s session for test1@bmp-develop.phoenix.mahsan.net/CodeFather: Connection failed: connection closed
02:55:32.588 [info] (sm_remove_connection_hook|bmp-develop.phoenix.mahsan.net) Timing started
02:55:32.588 [info] (sm_remove_connection_hook|bmp-develop.phoenix.mahsan.net) ejabberd_tcp_trace_user:unregister_session/3 got 32283ns
02:55:32.588 [info] (sm_remove_connection_hook|bmp-develop.phoenix.mahsan.net) Timing stopped
02:55:32.588 [info] (privacy_check_packet|bmp-develop.phoenix.mahsan.net) Timing started
02:55:32.588 [info] (privacy_check_packet|bmp-develop.phoenix.mahsan.net) mod_last:privacy_check_packet/4 got 9972ns
02:55:32.588 [info] (privacy_check_packet|bmp-develop.phoenix.mahsan.net) mod_privacy:check_packet/4 got 118585ns
02:55:32.589 [info] (privacy_check_packet|bmp-develop.phoenix.mahsan.net) All callbacks got 128557ns to run. Sorted running time:
        mod_last:privacy_check_packet/4 -> 9972ns
        mod_privacy:check_packet/4 -> 118585ns
02:55:32.589 [info] (privacy_check_packet|bmp-develop.phoenix.mahsan.net) Time calculations for all callbacks got 298045ns
02:55:32.589 [info] (privacy_check_packet|bmp-develop.phoenix.mahsan.net) Timing stopped
02:55:32.589 [info] (sm_receive_packet|bmp-develop.phoenix.mahsan.net) Timing started
02:55:32.589 [info] (sm_receive_packet|bmp-develop.phoenix.mahsan.net) mod_mam:sm_receive_packet/1 got 11188ns
02:55:32.589 [info] (sm_receive_packet|bmp-develop.phoenix.mahsan.net) Timing stopped
02:55:32.690 [info] (c2s_terminated|bmp-develop.phoenix.mahsan.net) ejabberd_c2s:process_terminated/2 got 102546399ns
02:55:32.690 [info] (c2s_terminated|bmp-develop.phoenix.mahsan.net) All callbacks got 5180271456ns to run. Sorted running time:
        ejabberd_c2s:process_terminated/2 -> 102546399ns
        mod_pubsub:on_user_offline/2 -> 5077725057ns
02:55:32.691 [info] (c2s_terminated|bmp-develop.phoenix.mahsan.net) Time calculations for all callbacks got 668166ns
02:55:32.691 [info] (c2s_terminated|bmp-develop.phoenix.mahsan.net) Timing stopped

```
</details>

#### Tracing one hook for 30s
<details>

```erlang
03:09:26.326 [info] (<0.558.0>) Accepted connection 127.0.0.1:40146 -> 127.0.0.1:5222
03:09:32.421 [info] (tcp|<0.558.0>) Accepted c2s PLAIN authentication for test1@bmp-develop.phoenix.mahsan.net by http backend from 127.0.0.1
03:09:33.266 [info] (tcp|<0.558.0>) Opened c2s session for test1@bmp-develop.phoenix.mahsan.net/CodeFather

(ejabberd@localhost)1> HookName = c2s_handle_info,
(ejabberd@localhost)1> AllHosts = <<"*">>,
(ejabberd@localhost)1> TracePid = <0.558.0>,
(ejabberd@localhost)1> TraceOpts = #{event_handler_options => #{output_function => fun io:format/2}},
(ejabberd@localhost)1> TraceTime = 30000, % 30s
(ejabberd@localhost)1> ok.
ok
(ejabberd@localhost)2> ejabberd_hooks:trace_on(HookName, AllHosts, TracePid, TraceOpts, TraceTime).
ok

(ejabberd@localhost)3> TracePid ! test.
(c2s_handle_info|bmp-develop.phoenix.mahsan.net) Timing started
(c2s_handle_info|bmp-develop.phoenix.mahsan.net) ejabberd_sm:c2s_handle_info/2 got 25269ns
test
(c2s_handle_info|bmp-develop.phoenix.mahsan.net) mod_conversation:c2s_handle_info/2 got 9886ns
(ejabberd@localhost)4> (c2s_handle_info|bmp-develop.phoenix.mahsan.net) mod_offline:c2s_handle_info/2 got 10063ns
(c2s_handle_info|bmp-develop.phoenix.mahsan.net) mod_pubsub:c2s_handle_info/2 got 9594ns
(c2s_handle_info|bmp-develop.phoenix.mahsan.net) ejabberd_c2s:process_info/2 got 116464ns
03:10:49.975 [warning] Unexpected info: test
(c2s_handle_info|bmp-develop.phoenix.mahsan.net) All callbacks got 171276ns to run. Sorted running time:
        mod_pubsub:c2s_handle_info/2 -> 9594ns
        mod_conversation:c2s_handle_info/2 -> 9886ns
        mod_offline:c2s_handle_info/2 -> 10063ns
        ejabberd_sm:c2s_handle_info/2 -> 25269ns
        ejabberd_c2s:process_info/2 -> 116464ns
(c2s_handle_info|bmp-develop.phoenix.mahsan.net) Time calculations for all callbacks got 1326643ns
(c2s_handle_info|bmp-develop.phoenix.mahsan.net) Timing stopped

(ejabberd@localhost)4> TracePid ! test.
test
03:11:19.646 [warning] Unexpected info: test
```
</details>

### CODE REVIEW

**Comment by badlop** [comment]
Hi! It's a nice feature. I didn't look into the implementation, I'm playing with it as an administrator, and found some comments regarding usability:

A) If all the measured times will be more than 1000ns, why not showing in μs? "414 μs" is easier to read than "414074ns"

B) Quite probably trace time will be at least 1 second always, so it could expect seconds and later Time*1000

C) For one single event, all those lines are logged, the most informative one is "All callbacks...", as it summarizes the others. I guess that's the only one worth reading. Unfortunately, there's no way to filter them, as all are "info".

<details>

```
2022-01-21 23:09:20.513618+01:00 [info] (disco_local_items|localhost) Timing started

2022-01-21 23:09:20.513985+01:00 [info] (disco_local_items|localhost) mod_announce:disco_items/5 got 77731ns 

2022-01-21 23:09:20.514469+01:00 [info] (disco_local_items|localhost) mod_configure:get_local_items/5 got 109997ns

2022-01-21 23:09:20.514733+01:00 [info] (disco_local_items|localhost) mod_pubsub:disco_local_items/5 got 6356ns

2022-01-21 23:09:20.514867+01:00 [info] (disco_local_items|localhost) mod_adhoc:get_local_commands/5 got 13689ns

2022-01-21 23:09:20.515403+01:00 [info] (disco_local_items|localhost) mod_disco:get_local_services/5 got 414074ns

2022-01-21 23:09:20.515699+01:00 [info] (disco_local_items|localhost) All callbacks got 621847ns to run. Sorted running time:
        mod_pubsub:disco_local_items/5 -> 6356ns
        mod_adhoc:get_local_commands/5 -> 13689ns
        mod_announce:disco_items/5 -> 77731ns
        mod_configure:get_local_items/5 -> 109997ns
        mod_disco:get_local_services/5 -> 414074ns

2022-01-21 23:09:20.515954+01:00 [info] (disco_local_items|localhost) Time calculations for all callbacks got 1371771ns

2022-01-21 23:09:20.520471+01:00 [info] (disco_local_items|localhost) Timing stopped

```
</details>

D) I wrote a frontend function to make my life easier, and allows me to start tracing with:
> ejabberd_hooks:trace(all, all, {user, "admin", "localhost", "tka1"}, undefined).

<details>

```erlang
trace(HookName1, HookHost1, {user, Username, Hostname, Resource}, TimeoutSeconds) ->
    Pid = ejabberd_sm:get_session_pid(list_to_binary(Username),
                                      list_to_binary(Hostname),
                                      list_to_binary(Resource)),
    trace(HookName1, HookHost1, Pid, TimeoutSeconds);
trace(HookName1, HookHost1, Pid, TimeoutSeconds) when is_pid(Pid)->
    HookName = case HookName1 of
               all -> '_';
               _ -> HookName1
           end,
    HookHost = case HookHost1 of
               all -> <<"*">>;
               _ -> list_to_binary(HookHost1)
           end,
    Opts = #{event_handler_options => #{output_function => fun io:format/2}},
    Timeout = case TimeoutSeconds of
                  undefined -> undefined;
                  _ -> TimeoutSeconds * 1000
              end,
    trace_on(HookName, HookHost, Pid, Opts, Timeout).
```
</details>

**Comment by pouriya** [comment]
Hi. You're right about the `timing` event handler. It's better to make time human-readable and yes we don't need each callback to be logged as long as we don't want to see the right order. By `timing` event handler, I just wanted to show you how the event handler functionality can get things done.

**Comment by pouriya** [comment]
> D) I wrote a frontend function to make my life easier ...

Since we trace a c2s process after all, I was planning to implement it in `ejabberd_c2s`:  
```erlang
% in ejabberd_c2s

trace_hook_for_next_session(Hook, Server, Opts, Timeout) ->
    % this function registers a fun for `c2s_init` hook.
    % first connection runs that fun and enables tracing and sends us a message to unregister the hook.
    % so we can trace all hooks after a c2s process is started
    % ...
    .

trace_session_hook(Hook, USR_or_Pid, Opts, Timeout) ->
    % USR_or_Pid: {User, Host, Resource} | Pid
    % ...
    .

**Comment by pouriya** [comment]
I'm going to change the `timing` event handler.

**Comment by pouriya** [comment]
New Example for `timing` event handler:  
<details>

```erlang

18:23:03.443 [info] (<0.558.0>) Accepted connection 127.0.0.1:41032 -> 127.0.0.1:5222
18:23:09.413 [info] (tcp|<0.558.0>) Accepted c2s PLAIN authentication for test1@bmp-develop.phoenix.mahsan.net by http backend from 127.0.0.1
18:23:10.283 [info] (tcp|<0.558.0>) Opened c2s session for test1@bmp-develop.phoenix.mahsan.net/CodeFather


1> ejabberd_hooks:trace_on(user_send_packet, "*", <0.558.0>, #{}, undefined).
ok

% send a message:
18:23:59.499 [info] (user_send_packet|bmp-develop.phoenix.mahsan.net|<0.558.0>|fold) Timing started
18:24:00.666 [info] (user_send_packet|bmp-develop.phoenix.mahsan.net|<0.558.0>|fold) All callbacks took 1.166007932s to run. Sorted running time:
        mod_vcard_xupdate:user_send_packet/1 -> 4.789μs
        mod_caps:user_send_packet/1 -> 4.883μs
        mod_privacy:user_send_packet/1 -> 7.13μs
        mod_conversation:user_send_packet/1 -> 12.689μs
        mod_mam:user_send_packet_strip_tag/1 -> 25.406μs
        mod_carboncopy:user_send_packet/1 -> 10.88456ms
        mod_mam:user_send_packet/1 -> 1.155068475s
18:24:00.666 [info] (user_send_packet|bmp-develop.phoenix.mahsan.net|<0.558.0>|fold) Time calculations for all callbacks took 237.267μs
18:24:00.666 [info] (user_send_packet|bmp-develop.phoenix.mahsan.net|<0.558.0>|fold) Timing stopped

% Update options and log for each callback too:
2> ejabberd_hooks:trace_on(user_send_packet, "*", <0.558.0>, #{event_handler_options => #{timing => #{output_for_each_callback => true}}}, undefined).
ok
 
% send a message                                                                                                                                   
3> 18:24:36.846 [info] (user_send_packet|bmp-develop.phoenix.mahsan.net|<0.558.0>|fold) Timing started
18:24:36.846 [info] (user_send_packet|bmp-develop.phoenix.mahsan.net|<0.558.0>|fold) mod_conversation:user_send_packet/1 took 20.626μs
18:24:36.847 [info] (user_send_packet|bmp-develop.phoenix.mahsan.net|<0.558.0>|fold) mod_privacy:user_send_packet/1 took 20.509μs
18:24:36.847 [info] (user_send_packet|bmp-develop.phoenix.mahsan.net|<0.558.0>|fold) mod_vcard_xupdate:user_send_packet/1 took 16.625μs
18:24:36.847 [info] (user_send_packet|bmp-develop.phoenix.mahsan.net|<0.558.0>|fold) mod_caps:user_send_packet/1 took 13.369μs
18:24:37.804 [info] (user_send_packet|bmp-develop.phoenix.mahsan.net|<0.558.0>|fold) mod_mam:user_send_packet/1 took 956.279552ms
18:24:37.804 [info] (user_send_packet|bmp-develop.phoenix.mahsan.net|<0.558.0>|fold) mod_carboncopy:user_send_packet/1 took 176.078μs
18:24:37.804 [info] (user_send_packet|bmp-develop.phoenix.mahsan.net|<0.558.0>|fold) mod_mam:user_send_packet_strip_tag/1 took 34.105μs
18:24:37.805 [info] (user_send_packet|bmp-develop.phoenix.mahsan.net|<0.558.0>|fold) All callbacks took 956.560864ms to run. Sorted running time:
        mod_caps:user_send_packet/1 -> 13.369μs
        mod_vcard_xupdate:user_send_packet/1 -> 16.625μs
        mod_privacy:user_send_packet/1 -> 20.509μs
        mod_conversation:user_send_packet/1 -> 20.626μs
        mod_mam:user_send_packet_strip_tag/1 -> 34.105μs
        mod_carboncopy:user_send_packet/1 -> 176.078μs
        mod_mam:user_send_packet/1 -> 956.279552ms
18:24:37.805 [info] (user_send_packet|bmp-develop.phoenix.mahsan.net|<0.558.0>|fold) Time calculations for all callbacks took 2.162244ms
18:24:37.805 [info] (user_send_packet|bmp-develop.phoenix.mahsan.net|<0.558.0>|fold) Timing stopped

3> 
```

</details>

**Comment by pouriya** [comment]
Now we can install multiple event handlers on a process.  
Default events:  
```erlang
% {EventName, EventArgs}:
{start_hook, [HookRunningArgs]}.
% BreakCallback is the callback that stops hooking by returning 'stop' or {'stop', _}:
{stop_hook, [HookRunningArgs, BreakCallback | undefined]}.
{start_callback, [Mod, Func, Args, Priority]}.
{stop_callback, [Mod, Func, Args, Priority, Result]}.
```

The `timing` event handler gets above events and generates new events:  
```erlang
% {EventName, EventArgs}:
{start_hook_timing, [HookRunningArgs, StartTime]}.
% BreakCallback is the callback that stops hooking by returning 'stop' or {'stop', _}:
{stop_hook_timing, [HookRunningArgs, BreakCallback | undefined, StartTime, StopTime, CallbackListTiming, CallbackListTotalTime]}.
{start_callback_timing, [Mod, Func, Args, Priority, CallbackStartTime]}.
{stop_callback, [Mod, Func, Args, Priority, Result, CallbackStartTime, CallbackStopTime]}.
```
The `timing` event handler also uses its own events to log timing info. Other event handlers can use above events too (e.g. exporting some timing metrics somewhere).

**Comment by pouriya** [comment]
@badlop about the **D** section in your comment; Is it okay to implement different API functions in `ejabberd_c2s` and `mod_muc` and `ejabberd_router`?

**Comment by pouriya** [comment]
@badlop ping

**Comment by pouriya** [comment]
@badlop ping

**Comment by badlop** [comment]
> Add process hook tracing

I have a basic question: this feature is for measuring one single process, one single hook, at a time, and providing those individual values. What practical usage did you find? Did this feature already pointed you to some interesting finding?

In a large system, to find the bottleneck functions that should be improved, I imagine it's preferable to view the function with most reductions, or other measure tha are not restricted to a specific hook, specific process, right?

> Is it okay to implement different API functions in ejabberd_c2s and mod_muc and ejabberd_router?

It depends on the purpose, how many lines of code, and what overhead it adds when not using hook tracing.

For what is that needed?

**Comment by pouriya** [comment]
> I have a basic question: ... What practical usage did you find? Did this feature already pointed you to some interesting finding?  

## About the generic implementation (not just the timing event handler)  
Different clients (and each client in different versions) use different features so their server process run **different code** and in Ejabberd **different code** most of the times means **different hook**. If we do not make a force update for some clients or some client versions, All of them are connecting to one `c2s` process but with different behaviors. This module can trace one or all hooks for a process and with different event handlers we can find different details for each process.  

#### My personal use case
I implemented a collector module that logs each hook with its parameters (transforms all Erlang terms to JSON) to files (I'm planning to send them to [Logstash](https://www.elastic.co/logstash/)). This module for some configured Jids starts tracing and collects their logs. Our test team members use this configured Jids and for all of their test scenarios I have a complete huge log file that describes many things! What if a client (not just our configured users for test team) shows some wired behavior? I just set its Jid to config and reload it and for its next session I will find out what is going on.  
Currently all log files will be compressed after session termination and are stored in files and served via a Webserver:  
Picsart_22-02-07_17-10-31-537   
What did I do to achieve this? Use a debugger? Use specific hooks to collect them? No, I just wrote a new tracing event handler function which is ~70 lines of code.  
Other solution: Use specific hooks to generate above logs and if in some cases you did not know what is going on, You have to read the code to find out what other code (hook) is running or you have to connect to server and trace the process by some debugger.  
This is my current use case and as I said earlier I'm planning to add another event handler that shows accumulator changes in `ejabberd_hooks:run_fold` calls. For example it will tell you what callback function removed what keys from `C2SState` maps and etc. This feature is useful (at least for me). When you (the Ejabberd team) release a new version, I have to read all of your new commits and merge the new code to my own code. What if something went wrong (just because in new version a key is removed from that map)? Most of the times I have to put `?DEBUG/2` everywhere to find it! 


## About the timing event handler
We develop new features, change or optimize a module and many more things. The timing event handler (which is just one but big function [here](https://github.com/processone/ejabberd/pull/3756/files#diff-42a9ab1d58ab50ab716ce010d785b4469c70abdbfdcad75a954ecafae7ad0ae6R564)) helps us to measure this changes simply and with different input data in real production service.  


> In a large system, to find the bottleneck functions ... right?  

It's not just for finding bottlenecks (The timing handler somehow is). It's about the different behavior of the same process that runs different hooks for different inputs.

**Comment by pouriya** [comment]
> It depends on the purpose, how many lines of code, and ... .

I told you how I want to do this [here](#issuecomment-1019175163).  Also I told you about the overhead in the [first comment](#issue-828027328)

**Comment by pouriya** [comment]
ping!!!

**Comment by badlop** [comment]
Hi! initially I was reluctant to recommend merging this PR because:
- A) Its usage isn't documented, just a few example calls
- B) Its usage seems mostly profitable only with quite some work involved. In other words, to use this tool for something, the admin or developer still has to invest quite some work writting his own scripts
- C) It failed compiling with Erlang 19
- D) I don't understand its internal implementation, which is important to me because its implementation isn't backed by any well-known developer, to give some confidence that any future bugs or problems can be addressed

On the other hand, looking at the bright side, this is an optional feature that doesn't affect normal behaviour and its code almost doesn't touch existing code.

So now I guess it could be merged and announce it as "experimental". That would hopefully allow to address:

- A) Once merged, we could attempt to document its usage in docs.ejabberd.im
- B) Over time, some example tools to benefit from it could be published in docs.ejabberd.im or in personal sites
- C) Compilation with Erlang 19 is easy to fix, just a pair of lines. Now it passes Dialyzer, etc.
- D) If problems arise in the future, and they can't be solved in time for the next ejabberd release, and nobody has any clue how to solve them, it's still possible to revert the feature, as its code is mostly stand-alone

What do you think @alexeyshch, @prefiks, @weiss ? Did I forget some reasons to not accept its merge?

**Comment by badlop** [comment]
Some time has passed, and I couldn't find strong reasons to decide if accept or reject this PR.

Let's take the optimistic path: merge it, document how to use it, and let people play with the feature

**Comment by pouriya** [comment]
👍🏼

**Pull request merged**
