### PR TITLE
Add sqlite support

### PR DESCRIPTION
**Pull request by saa**
Hi.
I added support SQLite3. But I have one question: for this case "Provide empty sqlite file structure as a starting point to use ejabberd with SQLite" (from issue #459), also need install sql/lite.sql. Path $PREFIX/lib/ejabberd/priv/sql/lite.sql it's ok?

### CODE REVIEW

**Comment by zinid** [comment]
Hi, seems like Travis has failed.
Also, what's up with Redis? Why did you remove it from the configure script?

**Comment by zinid** [comment]
Another issue is indentation (in YAML file): please don't touch empty lines or spaces, it will produce conflicts on merging.

**Comment by saa** [comment]
I forked before changes were with redis.
Thank you for review. I will fix and push again.

**Comment by saa** [comment]
Maybe better create new pull request? Without changes in YAML with empty lines or spaces.

**Comment by zinid** [comment]
Yes, I close this one

**Comment by mremond** [comment]
@saa Thanks, Please send us a pull request that is clean for integration, it will help.

Regarding your question: Mnesia database is created in $PREFIX/var/lib/ejabberd/
We should probably create sqlite empty structure in:
$PREFIX/var/lib/ejabberd/ejabberd-sqlite/lite.sql

Note that if the file already exist, it should not be overwritten to avoid data loss, but should be created as lite.sql-new

@zinid does it make sense ?

**Comment by saa** [comment]
@mremond copy sql schema to $PREFIX/var/lib/ejabberd/ejabberd-sqlite/lite.sql from sql/lite.sql?

I wanted copy lite.sql to priv dir $PREFIX/lib/ejabberd/priv/sql/lite.sql. Maybe I misunderstood?

**Comment by mremond** [comment]
What does lite.sql contain ? Is it sqlite database schema or is it database file itself (but empty) ?

**Comment by saa** [comment]
It's sqlite database schema

**Comment by saa** [comment]
And about: "Provide empty sqlite file structure as a starting point to use ejabberd with SQLite", at now I do it when init ejabberd_odbc_sup.

**Pull request closed without merging**
