### PR TITLE
Support SASL GSSAPI authentication

### PR DESCRIPTION
**Pull request by lemenkov**
This PR is based on patchset floating around in internet since 2009.

Patchset since then was improved by @badlop, Fyodor Kupchik (https://launchpad.net/~ferimy), Konstantin L. Metlov (https://launchpad.net/~metlov), and many others.

This particular version was tested against working Kerberos installation at Fedora Project. Thanks for @bowlofeggs and @puiterwijk for that!

For the record - this is a patchset's breakdown:

* https://github.com/lemenkov/ejabberd/compare/3114f5c...75c1389
* https://github.com/lemenkov/ejabberd/tree/fedora-16.12-gssapi-test

This PR closes bug #1586.

### CODE REVIEW

**Comment by zinid** [comment]
Several issuer I found quickly:
1) `try_start_gssapi()` should be called from inside cyrsasl_gssapi:start/1, obviously;
2) Attempt to attach directly to `ejabberd_sup`: `master` won't even start with this, it will get stuck in deadlock when starting `cyrsasl` gen_server;
3) Why we need to attach some third-party software (`esasl`) to local supervisor is beyond me: this suggests `esasl` itself has design flaws;
4) We cannot return `{error, <<"not-authorized">>}` or something like that in new ejabberd API
5) Auth module is not included in `{ok, [{username, Authid}, {authzid, Authzid}]}`.

Note these are problems I detected quickly in a couple of seconds reading the module, I think I can find more with deep reading.

**Comment by lemenkov** [comment]
@zinid thanks for the quick answer!

Regarding esasl - indeed it doesn't have optimal design. We have to use it because "it just works". Later we should replace it with a better solution (yet to be written).

**Comment by zinid** [comment]
The software with such design cannot "just work". I looked inside it and it looks like shit.
You see, if something goes wrong and a user will report a bug, who will handle this?

**Comment by lemenkov** [comment]
@zinid it actually can work, so no need to throw such rhetorical questions :). We plan to rewrite it later. We kept it as is just to focus on actual testing of this feature (otherwise there will be too much moving parts). So it will be rewritten eventually.

Just for the record - I see this PR mostly as a RFE, not yet ready for inclusion. And I'm happy to receive any comments and critics.

**Comment by zinid** [comment]
I'm acutally fine with adding normal OTP structure to `esasl` and removing at least those glitches I have already mentioned.

**Comment by lemenkov** [comment]
@zinid I did a few restructuring changes here:

https://github.com/lemenkov/esasl/tree/rebarize

At least it builds with rebar now, although codebase is still the same.

**Comment by Neustradamus** [comment]
Any news?
We arrive in 2019 ^^

**Comment by sim0nx** [comment]
Any news on this ? :-)

**Comment by zinid** [comment]
None of the issues I mentioned are fixed, so no, no news.

**Comment by Neustradamus** [comment]
@lemenkov: Any news on it?

**Comment by lemenkov** [comment]
> @lemenkov: Any news on it?

Nope, unfortunately. I am no longer using XMPP in any way.

**Comment by licaon-kter** [comment]
@lemenkov /close this then

**Comment by Neustradamus** [comment]
@licaon-kter: The code is good if it is not perfect, one people can update it...

**Comment by licaon-kter** [comment]
@Neustradamus the code is almost 4 years old, the coder didn't even show interest all these years and doesn't care anymore. _Let it go_

**Comment by Neustradamus** [comment]
@dequbed has added a PR: https://github.com/processone/xmpp/pull/56: WIP, thanks!

**Pull request closed without merging**
