### PR TITLE
Support XEP-0357: Push Notifications

### PR DESCRIPTION
**Pull request by weiss**
This adds two modules (and a few helper functions to other modules):

- `mod_push` implements (the XMPP server part of) [XEP-0357: Push Notifications][1], with the [business rules suggested by Daniel Gultsch][2].
- `mod_push_keepalive` tries to keep the XEP-0198 session alive for disconnected (but reachable) push clients, mostly to make push notifications work for [standard][3] MUC rooms. The idea is to not let the session expire unless the client failed to resume it after a push notification. (Large servers might want to disable this to save resources.)

SQL/Riak support is still missing.

[1]: https://xmpp.org/extensions/xep-0357.html
[2]: https://mail.jabber.org/pipermail/standards/2016-February/030925.html
[3]: https://xmpp.org/extensions/xep-0045.html

### CODE REVIEW

**Comment by zinid** [comment]
Finally :)

**Comment by cwildfoerster** [comment]
Whats missing for merging?

**Comment by cromain** [comment]
@weiss just ping me when you think it's ready for merge. you may add other backends later after 17.08.

**Comment by weiss** [comment]
Yes, I think this can be merged.

**Comment by erdii** [comment]
where can i find the documentation for using mod_push with ejabberd?

**Comment by weiss** [comment]
> where can i find the documentation for using mod_push with ejabberd?

You can simply enable `mod_push` without options as [in the sample configuration][1].  Adding some documentation is on my to-do list.

[1]: https://github.com/processone/ejabberd/blob/b23d5754e81fe27de16e57c28644d83c43dc169d/ejabberd.yml.example#L792

**Comment by erdii** [comment]
Thank you!

**Comment by manthan29** [comment]
We have been struggling to activate push notifications. Can anyone point me to the documentation as to how can I enable push notification with FCM the server. Also what do we need to do from the client application.

**Comment by weiss** [comment]
See https://github.com/processone/ejabberd/issues/2109#issuecomment-379220262

**Comment by gylraj** [comment]
does it support Voip push?

**Comment by zinid** [comment]
@gylraj no, whatever that means.

**Comment by licaon-kter** [comment]
@gylraj ejabberd sends a push request, it depends on your app and push server to register with Apple as a VoIP app to be able to get a VoIP push, else it will get a standard push.

**Comment by fingertips-solutions** [comment]
any documentation for this how can we use it with apple p8 certificates ?

**Comment by licaon-kter** [comment]
@fingertips-solutions this concerns ejabberd how? What push server do you use for your app?

**Comment by fingertips-solutions** [comment]
Apple apns
  

  
  

  
  
>

**Comment by weiss** [comment]
@fingertips-solutions, from [the docs][1]:

> This module implements the XMPP server's part of the push notification solution specified in XEP-0357. It does not generate, for example, APNS or FCM notifications directly. Instead, it's designed to work with so-called "app servers" operated by third-party vendors of mobile apps.

[1]: https://docs.ejabberd.im/admin/configuration/#mod-push

**Pull request merged**
