### PR TITLE
mod_shared_roster_ldap post merge fixes to upstream

### PR DESCRIPTION
**Pull request by porridge**
Please ignore the previous pull request, still discovering how this github thing works.
This one has a corrected commit range. My branch is based on 2.1.x, not master!

 Hello,

Most changes in this branch are fixes to documentation that should have been applied at the moment mod_shared_roster_ldap was incorporated into the upstream project.

There are also some minor code refactorings: simplifications and cleanups.

Please review and comment and/or pull.

Marcin

### CODE REVIEW

**Comment by Neustradamus** [comment]
Always possible for 18.12+?

**Comment by porridge** [comment]
Cleaning up stale PRs.

**Comment by Neustradamus** [comment]
porridge: :/

**Comment by Neustradamus** [comment]
@porridge: :/

**Pull request closed without merging**
