### PR TITLE
Fix dependencies issue with last release of rebar3

### PR DESCRIPTION
**Pull request by niamtokik**
Hi,

I am running on OpenBSD-current, with Erlang R21, and locally builded rebar3.

```sh
$ rebar3 version
rebar 3.13.2 on Erlang/OTP 21 Erts 10.2
```

I was originally using rebar3 version 3.14.0-rc2 and made a fallback to 3.13.2 to see if it was due to my testing version. So, I had trouble with getting dependencies, even after removing `_build` and `${HOME}/.cache/rebar3/hex` directories. The error is:

```
$ DEBUG=1 rebar3 get-deps                                          
===> Evaluating config script "rebar.config.script"                                                             
===> Rebar3 detected a lock file from a newer version. It will be loaded in compatibility mode, but important information may be missing or lost. It is recommended to upgrade Rebar3.
===> 21.2 satisfies the requirement for minimum OTP version 18                                                  
===> Expanded command sequence to be run: [{default,app_discovery},                                             
                                                  {default,install_deps},                                       
                                                  {default,lock},                                               
                                                  {default,'get-deps'}]                                         
===> Provider: {default,app_discovery}                                                                          
===> 21.2 satisfies the requirement for minimum OTP version 18                                                  
===> Not adding provider hex user from module rebar3_hex_user because it already exists from module rebar3_hex_user
===> Not adding provider hex cut from module rebar3_hex_cut because it already exists from module rebar3_hex_cut
===> Not adding provider hex key from module rebar3_hex_key because it already exists from module rebar3_hex_key
===> Not adding provider hex owner from module rebar3_hex_owner because it already exists from module rebar3_hex_owner
===> Not adding provider hex repo from module rebar3_hex_repo because it already exists from module rebar3_hex_repo
===> Not adding provider hex docs from module rebar3_hex_docs because it already exists from module rebar3_hex_docs
===> Not adding provider hex search from module rebar3_hex_search because it already exists from module rebar3_hex_search
===> Not adding provider hex revert from module rebar3_hex_revert because it already exists from module rebar3_hex_revert
===> Not adding provider hex retire from module rebar3_hex_retire because it already exists from module rebar3_hex_retire
===> Not adding provider hex publish from module rebar3_hex_publish because it already exists from module rebar3_hex_publish
===> Not adding provider asn compile from module provider_asn1_compile because it already exists from module provider_asn1_compile
===> Not adding provider asn clean from module provider_asn1_clean because it already exists from module provider_asn1_clean
===> Provider: {default,install_deps}
===> Verifying dependencies...                                                                                  
===> Package not found in any repo: base64url v1.0
```

Same issue with another dependency:

```
$ rebar3 get-deps                                                                                                                                                                  
===> Rebar3 detected a lock file from a newer version. It will be loaded in compatibility mode, but important information may be missing or lost. It is recommended to upgrade Rebar3.
===> Verifying dependencies...                                                                                  
===> Package not found in any repo: p1_acme 1.0.6
```

After testing, I modified the `rebar.conf` file based on official [documentation](https://www.rebar3.org/docs/dependencies). Works as expected. Can you confirm you have the same issue on your side, or I am the only one?

### CODE REVIEW

**Comment by prefiks** [comment]
Hello,

Looks like we forgot to publish new release of p1_acme in hex, so that's why you are getting this error, i will ask person responsible for managing this to upload new version.

**Comment by prefiks** [comment]
And new version was updated, could you check if it works for you now without this patch?

There is code in rebar.config.script that converts those dependency lines using git, to hex on rebar3, what your patch does is just prevents it from parsing it so it uses git instead, but that also have a problem that it's not accepted by rebar2. So if we want to use git instead of hex, better way would be to disable that conversion in .script code.

**Comment by niamtokik** [comment]
Hi,

It seems I have another issue. During dependencies compilation, the configure part seems broken. 

```txt
$ DEBUG=1 rebar3 compile
===> Port Cmd: sh -c 'if test ! -f config.status -o ../../config.status -nt config.status; then (CFLAGS="-g -O2 -Wall" CPPFLAGS="-g -O2 -Wall" LDFLAGS="" ./configure ); fi'
Port Opts: [{cd,"/home/user/projects/github/ejabberd/_build/default/lib/fast_yaml"},
            {env,[{"REBAR_DEPS_DIR",
                   "/home/user/projects/github/ejabberd/_build/default/lib"},
                  {"REBAR_BUILD_DIR",
                   "/home/user/projects/github/ejabberd/_build/default"},
                  {"REBAR_ROOT_DIR","/home/user/projects/github/ejabberd/."},
                  {"REBAR_CHECKOUTS_DIR",
                   "/home/user/projects/github/ejabberd/_checkouts"},
                  {"REBAR_PLUGINS_DIR",
                   "/home/user/projects/github/ejabberd/_build/default/plugins"},
                  {"REBAR_GLOBAL_CONFIG_DIR","/home/user/.config/rebar3"},
                  {"REBAR_GLOBAL_CACHE_DIR","/home/user/.cache/rebar3"},
                  {"REBAR_TEMPLATE_DIR","/home/user/.config/rebar3/templates"},
                  {"REBAR_APP_DIRS",
                   "_build/default/apps/*:_build/default/lib/*:_build/default/."},
                  {"REBAR_SRC_DIRS","_build/default/src"},
                  {"ERLANG_ERTS_VER","10.2"},
                  {"ERLANG_ROOT_DIR","/usr/local/lib/erlang21"},
                  {"ERL","/usr/local/lib/erlang21/bin/erl"},
                  {"ERLC","/usr/local/lib/erlang21/bin/erlc"},
                  {"ERLANG_ARCH","64"},
                  {"ERLANG_TARGET","21.2-x86_64-unknown-openbsd6.7-64"},
                  {"ERLANG_LIB_DIR_erl_interface",
                   "/usr/local/lib/erlang21/lib/erl_interface-3.10.4"},
                  {"ERLANG_LIB_VER_erl_interface","3.10.4"}]},
            exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof]

sh: ./configure: not found
===> Hook for {pc,compile} failed!
```

I fixed this issue by disabling the configure part.

**Comment by nosnilmot** [comment]
Please see these PRs for rebar3 required changes:

ejabberd: https://github.com/processone/ejabberd/pull/3368

epam: https://github.com/processone/epam/pull/10
esip: https://github.com/processone/esip/pull/9 https://github.com/processone/esip/pull/10
ezlib: https://github.com/processone/ezlib/pull/3
fast_tls: https://github.com/processone/fast_tls/pull/48
fast_xml: https://github.com/processone/fast_xml/pull/42
fast_yaml: https://github.com/processone/fast_yaml/pull/17
stringprep: https://github.com/processone/stringprep/pull/10
xmpp: https://github.com/processone/xmpp/pull/51 & https://github.com/processone/xmpp/pull/52

**Comment by badlop** [comment]
@nosnilmot, I wonder if those changes that fix support for rebar3, will not break support for rebar2...

After applying those changes, did you check all works correctly with rebar2 too?

**Comment by nosnilmot** [comment]
> @nosnilmot, I wonder if those changes that fix support for rebar3, will not break support for rebar2...
> 
> After applying those changes, did you check all works correctly with rebar2 too?

Yes, all still works correctly with rebar2 - also confirmed by the fact that all the Travis CI builds, which use rebar2, passed.

The majority of these changes are adding files to include in the hex packages, which are not used by rebar2 anyway.

**Comment by weiss** [comment]
Building with Rebar3 should now be fixed thanks to @nosnilmot (see #3368).

**Pull request closed without merging**
