### PR TITLE
acl for mam preferences

### PR DESCRIPTION
**Pull request by ChaosKid42**
I'd like to keep users from changing default mam policy. Therefore I propose a new option of mod_mam `access_prefernces` which defaults to true.

I will happily write an entry for the documentation if my PR is accepted.

### CODE REVIEW

**Comment by weiss** [comment]
To be honest, I'd turn this into an access rule (and call the option `access_preferences` or so).

Sorry, I'm not trying to annoy you :wink:

**Comment by zinid** [comment]
I agree with @weiss: we definitely need to reuse existing ACL framework for things like this.

**Comment by ChaosKid42** [comment]
I see your point. I'll try to work in that direction maybe by end of this week.

**Comment by ChaosKid42** [comment]
@weiss Maybe now it is acceptable.

**Comment by weiss** [comment]
[Merged][1], thanks.

[1]: https://github.com/processone/ejabberd/commit/fb068557b29a870390ea66170566766e8a96fca9

**Pull request closed without merging**
