### PR TITLE
ref: fix WS typos

### PR DESCRIPTION
**Pull request by pouriya**

### CODE REVIEW

**Comment by pouriya** [comment]
Hi. I forgot to change my email address and This is really really bad and I'm not allowed to submit a public PR with that email address! Could you change that to `pouriya.jahanbakhsh@gmail.com`? Sorry, my bad.

**Comment by badlop** [comment]
Hi, I am not git expert, so I don't know if it's possible to modify a commit already pushed. If there's some way, tell me.

Another solution would be that I revert that PR, and later you submit a new PR with the desired account. Would that be acceptable for you?

**Comment by pouriya** [comment]
> I am not git expert, so I don't know if it's possible to modify a commit already pushed. If there's some way, tell me.  

IIRC it requires a force push which is not good.

> Another solution would be that I revert that PR, and later you submit a new PR with the desired account/email. Would that be acceptable for you?  

Yesssssssssss, ofc. Thank you.

**Comment by nosnilmot** [comment]
> Another solution would be that I revert that PR, and later you submit a new PR with the desired account/email. Would that be acceptable for you?

Unless you actually delete the original commit and do a force push (requiring anyone who has since fetched to jump through hoops to get their clone in sync again), the email address will remain in the git history on the original commit and the revert/new PR will just draw attention to it.

**Comment by pouriya** [comment]
@nosnilmot Is it ok?
```sh
$ git rebase -i HEAD~20
# change 'pick' to 'edit' for the commit
Stopped at b5bafca6...  ref: fix WS typos
You can amend the commit now, with

  git commit --amend 

Once you are satisfied with your changes, run

  git rebase --continue
$ git commit --amend --author="Pouriya <pouriya.jahanbakhsh@gmail.com>"
[detached HEAD 791627ee] ref: fix WS typos
 Author: Pouriya <pouriya.jahanbakhsh@gmail.com>
 Date: Sat Jun 12 20:27:30 2021 +0430
 2 files changed, 40 insertions(+), 40 deletions(-)
 $ git rebase --continue                                                
Successfully rebased and updated refs/heads/master.
$ git push --force-with-lease origin master
```

**Comment by nosnilmot** [comment]
> @nosnilmot Is it ok?

No, absolutely not, nothing in my earlier comment should be taken to indicate that I support a force push solution!

It is best to just let it be, and take more care in the future.

**Comment by pouriya** [comment]
If you don't want to do a force push, I don't blame you.

**Pull request merged**
