### PR TITLE
Update el.msg

### PR DESCRIPTION
**Pull request by rafaila42**
Several translation improvements, hopefully correct :)

### CODE REVIEW

**Comment by licaon-kter** [comment]
@rafaila42 why not use the translation platform? https://hosted.weblate.org/projects/ejabberd/ejabberd/ ;)

**Comment by rafaila42** [comment]
I wasn't aware of it, I'm a total newb. But it looks like a mess

**Comment by badlop** [comment]
So, you noticed that the `priv/msgs/` path has the files with translatable strings. And for each language, you noticed two files: one `*.msg` and one `*.po`. And you decided to update `el.msg` instead of `el.po`.

Why? I imagine the file syntax in*.msg looked easier to modify with a text editor that *.po, right?

In fact, the files to edit are `*.po`, and there are many great tools to edit them easily, without pain, and it informs about any syntax mistake. That is explained in https://docs.ejabberd.im/developer/extending-ejabberd/localization/ but I imagine that section is quite hidden in the documentation page.

I guess that all the `*.msg` files should contain some lines in the beginning like this, to point beginners in the right direction:
```
%% -*- coding: utf-8 -*-
%% DO NOT EDIT THIS FILE
%% This file is automatically generated from the *.po file, for details please check
%% https://docs.ejabberd.im/developer/extending-ejabberd/localization/
{" (Add * to the end of field to match substring)"," (Afegix * al final d'un camp per a buscar subcadenes)"}.
{" has set the subject to: "," ha posat el tema: "}.
{"# participants","# participants"}.
...
```

**Comment by badlop** [comment]
Good news! I was able to manually apply your improvements into `el.po`, and recompile `el.msg`.

If you want to take a look at missing strings and fuzzy (half-way tanslated) strings, check `priv/msgs/el.po` 

Also, if you install some gettext editor, it's a lot easier to edit it. For example, I use Poedit.

**Comment by rafaila42** [comment]
Please, excuse my ignorance!
You are right, msg's looked easier! ;) , but with Poedit, it is piece of cake!

Anyway now, I finished locally all translation on el.po, but uploading it is a little bit unclear (and I'm affraid of you too). Should I make another pull request?
Please kindly advise.

**Comment by badlop** [comment]
Generating a new PR based in the newest code would have been preferable. But anyway, I've manually applied your changes. Now Greek translation is 100% complete :)

**Comment by Neustradamus** [comment]
@rafaila42: Please look weblate, it is really easy.
I have requested to have better translations and easy system.

**Pull request closed without merging**
