### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by toopay**
Add the `autogen.sh` execution to generate a new autoconf prior anything else.

### CODE REVIEW

**Comment by zinid** [comment]
autogen.sh is only needed when building from git

**Comment by toopay** [comment]
@zinid I'm aware of that. But the current README doesn't explicitly said to : checkout to `2.1.x` branch's `src` prior execute `./configure`, so its pretty logical to assume that current build instruction is for master branch, no?

**Comment by zinid** [comment]
I don't know, I thought this README is for tarball actually :)

**Comment by weiss** [comment]
@toopay, what README are you talking about?  ejabberd's [current README file][1] doesn't mention the Git repository, as far as I can see.  I think developers who use the repo are expected to know what they're doing :-)

[1]: https://raw.githubusercontent.com/processone/ejabberd/ad4b41730e488c75b84894f2ff311f5409f32543/README

**Comment by toopay** [comment]
> I think developers who use the repo are expected to know what they're doing

Fair enough.

**Comment by badlop** [comment]
By the way, the Guide includes a small paragraph about Git, so I've added that comment there.

**Pull request closed without merging**
