### PR TITLE
Issue #456: Attempt to auto restart mod_irc in case of crash

### PR DESCRIPTION
**Pull request by kansi**
changed mod_irc from temporary to transient child and placed it under ejabberd_mod_irc_sup supervisor.

### CODE REVIEW

**Comment by zinid** [comment]
ejabberd_mod_irc_sup is a `simple_one_for_one` supervisor. AFAIK, you cannot attach transient children to it, as it doesn't even keep any childspecs.

**Comment by kansi** [comment]
yeah. looked at ejabberd_sup its one_for_one, I think it was correct previously to have mod_irc under ejabberd_sup but as transient child so that it can be restarted.

**Comment by mremond** [comment]
@zinid How does it look, now ?

**Comment by zinid** [comment]
@mremond more or less. But now I don't see any purposes of ejabberd_mod_irc_sup :)

**Comment by mremond** [comment]
Isn't that mod_irc_sup for the connections themselves ?

**Comment by badlop** [comment]
mod_irc is not maintaned anymore. The code was moved to ejabberd-contrib in June (3a5d2dbed8f089b112eba7998e2ad0d2508f01cb), so that it doesn't get lost. If this problem is still present and somebody wants to fix it, a new ticket in [ejabberd-contrib](https://github.com/processone/ejabberd-contrib) can be created, referencing this old one.

**Pull request closed without merging**
