### PR TITLE
EJAB-1659: Implement pubsub#expire and temporal pubsub options

### PR DESCRIPTION
**Pull request by nbruning**

### CODE REVIEW

**Comment by nbruning** [comment]
Node option "tempsub" can easily be ported to ejabberd 16.
The subscription option "presence#expire" doesn't work anymore due to 1a32f20c.

**Comment by Neustradamus** [comment]
@nbruning: Can you look for an update of your code?
It will be nice to have a merging...
Thanks in advance.

**Comment by nbruning** [comment]
@Neustradamus this PR was so old, i've decided to create a new one with just the tempsub feature: #3510.

I'll close this PR.

**Comment by Neustradamus** [comment]
@nbruning: Thanks a lot for your reply and your new PR :)

**Pull request closed without merging**
