### PR TITLE
Add SQLite support

### PR DESCRIPTION
**Pull request by saa**

### CODE REVIEW

**Comment by zinid** [comment]
Did you run the tests locally? Why don't they work?

**Comment by saa** [comment]
Yes, I ran locally. And get error with connection timeout for 4 tests.

**Comment by saa** [comment]
@zinid I found reason and I'll fix it and push.

**Comment by zinid** [comment]
Awesome!

**Comment by saa** [comment]
Strange. make xref failed, local is ok.

**Comment by zinid** [comment]
Most likely you're using some relatively new functions introduced in recent Erlang versions. Such as erlang:binary_to_integer/1,2.

**Comment by zinid** [comment]
Regarding your last commit: we typically do not use such coding approach, i.e. we're not using guard functions such as is_list, is_integer and so on for type verification: this should be done by Dialyzer. Also, binary_to_integer(5) breaks the function semantics.
Why do you need such tricks?

**Comment by saa** [comment]
I don't use binary_to_integer/1,2.

And about trick: sqlite3 return integer when is integer. In ejabberd code use jlib:binary_to_integer for value return from db. So I use this trick.

**Comment by zinid** [comment]
If you want this hack, then use it in a local code, do not spread this on all code via jlib.erl. Such `defensive code` leads to hard-to-track errors.

**Comment by saa** [comment]
Ok. I'll fix it.

**Comment by mremond** [comment]
@saa Hi, how is the fix going ?

**Comment by saa** [comment]
@mremond Hi. Sorry, I digress.

@zinid It's ok? No need to fix?

**Comment by zinid** [comment]
I fixed and improved everything

**Comment by saa** [comment]
@zinid you are cool. Thank you.

**Pull request merged**
