### PR TITLE
XMPP + ejabberd

### PR DESCRIPTION
**Pull request by Neustradamus**
Replace:
- Jabber to XMPP
- Ejabberd to ejabberd

### CODE REVIEW

**Comment by badlop** [comment]
This was already submitted in https://github.com/processone/ejabberd/pull/3469, reviewed, and some specific changes were rejected. Why are they submitted again?

**Comment by Neustradamus** [comment]
@badlop: I know that win32 folder is very old.
You can remove no?
Same for transport files?

Why you do not accept changes in other files?

**Comment by badlop** [comment]
> You can remove no?

Probably yes, but I am not 100% sure. So, I've filed https://github.com/processone/ejabberd/issues/3487 so that can be discussed.

> Why you do not accept changes in other files?

XEP-0078 is related to Jabber, so that must be mentioned.

"Outdated Jabber bots" are "Outdated Jabber bots". They are not "Outdated XMPP bots".

Websocket and BOSH informative pages: as those pages are displayed to end users that may not know "XMPP" term, both terms should be displayed, Jabber and XMPP

**Comment by Neustradamus** [comment]
@badlop:
-> Jabber is the old name of XMPP
- https://www.jabber.org/
- https://en.wikipedia.org/wiki/XMPP

-> Jabber bots = XMPP bots

BOSH are XEPs, XMPP Extensions:
- https://xmpp.org/extensions/xep-0124.html
- https://xmpp.org/extensions/xep-0206.html

WebSocket is an RFC:
- https://tools.ietf.org/html/rfc6455

XMPP and WebSocket is an RFC:
- https://tools.ietf.org/html/rfc7395

**Comment by Neustradamus** [comment]
@badlop: Can you reopen my PR?

**Comment by badlop** [comment]
Can you stop lobbying?

**Comment by Neustradamus** [comment]
@badlop: But it is to be only perfect :)
It is better to reopen than a new PR...

**Pull request closed without merging**
