### PR TITLE
Include stanza ID with archived offline messages

### LINKED ISSUE #1480: Missing stanza-id in Message (from offline storage)
> What version of ejabberd are you using?

17.01.45

> What operating system (version) are you using?

Ubuntu Linux

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I'm receiving a message without a stanza-id. It might be from the offline storage.

```xml
<message xmlns="jabber:client" to="romeo@example.com" from="juliet@example.com" type="chat" id="402466435698">
    <delay xmlns="urn:xmpp:delay" from="example.com" stamp="2017-01-23T16:37:22.445939Z">Offline storage</delay>
    <body>...</body>
</message>
```

To not having duplicate messages in the local client archive, the stanza-is are needed in all messages.

### PR DESCRIPTION
**Pull request by weiss**
Fixes #1480.

### CODE REVIEW

**Comment by zinid** [comment]
We probably don't need to pass `From` and `To` anymore, as it's a part of `#message{}`. Since we decided to break the hook's backward compatibility, it is now a good moment doing this (I already did that in a lot of hooks).

**Comment by weiss** [comment]
Ah, okay.  I'll update the patch.

**Comment by weiss** [comment]
I've updated the patch to make it work with the current code (without separate `From` and `To` arguments).

**Comment by zinid** [comment]
Thanks :smiley_cat:

**Pull request merged**
